### ISSUE TITLE
Type Index - more examples of common types

### ISSUE THREAD

**Issue by elf-pavlik** [solid/solid#101]
[Current proposal of type index](https://github.com/solid/solid/blob/master/proposals/data-discovery.md) has examples of
* `vcard:AddressBook`
* `sioc:Post`

IMO having reference with examples of commonly used types can improve interoperability. It could possibly find place in https://github.com/solid/vocab

http://rdfs.org/sioc/spec/#sec-overview
SIOC has superclass [`sioc:Container`](http://rdfs.org/sioc/spec/#term_Container) with a subclass [`sioc:Forum`](http://rdfs.org/sioc/spec/#term_Forum)

http://rdfs.org/sioc/spec/#sec-modules
SIOC Types Module specifies additional subclasses of [`sioc:Container`](http://rdfs.org/sioc/spec/#term_Container)
> Container: AddressBook, AnnotationSet, AudioChannel, BookmarkFolder, Briefcase, EventCalendar, ImageGallery, ProjectDirectory, ResumeBank, ReviewArea, SubscriptionList, SurveyCollection, VideoChannel, Wiki.

as well as subclasses of [`sioc:Forum`](http://rdfs.org/sioc/spec/#term_Forum) (itself subclass of [`sioc:Container`](http://rdfs.org/sioc/spec/#term_Container))
> Forum: ArgumentativeDiscussion, ChatChannel, MailingList, MessageBoard, Weblog

This looks like a decent starting point. 

BWT shouldn't Type Index use `sioct:Weblog` instead of `sioc:Post`?

I also start working on [Talent app](https://github.com/hackers4peace/o-app-talent) which will allow to add skills/competences using [The Cognitive Characteristics Ontology](http://smiy.sourceforge.net/cco/spec/cognitivecharacteristics.html), where I can discuss what type I should use in a Type Index? ( maybe solid/vocab )

In [Karma app](https://github.com/hackers4peace/o-app-karma) I plan to switch to http://prefix.cc/flow which @melvincarvalho uses in app he works on, so we could also discuss somewhere how to use Type Index for that :smile:

**Comment by dmitrizagidulin** [comment]
Yeah, I think the `solid/vocab` repo is the right place for those type of questions (and of collating commonly used types).

> BWT shouldn't Type Index use `sioct:Weblog` instead of `sioc:Post`?

Depends on what you're going for. I was demonstrating the usage of both `solid:instance` (for things like AddressBook and Weblog) and of `solid:instanceContainer` (for individual resources like Post).

**Comment by elf-pavlik** [comment]
Thanks! I'll make PR to solid/vocab with a draft of a page to which can serve as a reference for suggested types to use in applications.
