### ISSUE TITLE
please clarify the relationship of solid and databox.me

### ISSUE THREAD

**Issue by dduran1967** [solid/solid#126]
I'm a true believer in the cause of user-centric data, so much so that I'm ready to go all-in and  reorganize my world around solid, and contribute my ideas, experience and developer resources to promote and improve the platform, create a community of developers and enable them to create amazing, useful things with solid right now.  

The only thing giving me pause is databox.me.   Is db.me a playground for education and demonstration or is db.me the preferred provider of solid as is currently represented here: https://solid.github.io/solid-idps/ ?   Obviously for someone like myself, this is a critical distinction.  Thanks for your help.

**Comment by dmitrizagidulin** [comment]
Hi @dduran1967, thank you for the question.

`databox.me` (and `databox2.com`, etc) are simply playgrounds/reference account providers. We want people to be able to try out Solid without actually spinning up their own servers.

**Comment by dmitrizagidulin** [comment]
The https://solid.github.io/solid-idps/ link that you mentioned was part of an earlier UI for signups and signins. And I think the `recommended` tag was more to denote that db.me was recommended over rww.io (especially since now it has been deprecated/taken offline).

**Comment by dduran1967** [comment]
Excellent. Looks like I've found the project for me.  Let's go change the world!

**Comment by melvincarvalho** [comment]
@dduran1967 I am hoping to start a solid provider at https://solid.live/ ( not yet live, ironically! :) )

Currently I would like to work out how to provision users with storage and bandwidth limits.  

If you are interested in running a public solid server too, I would be interested in collaboration.

**Comment by dduran1967** [comment]
@melvincarvalho - absolutely.   We're in the process of implementing solid in idp mode for a customer as a managed service - so we'll be finding all the bumps in the process and finding solutions or workarounds.  Would be great to start building a community for solid implementers / providers.  Ping me on gitter or email direct anytime.

**Comment by jimscarver** [comment]
Hello solid community!

DivvyDAO.org is creating a bring your own identity (BYOID) id aggregation
be your own idp. Solid is a perfect replacement for the Synereo.com Alpha
released earlier this year but abandoned in the last month in a split
between synereo.com and rchain.coop

We exposed a number of synereo alpha nodes on home computers through ssh
tunnels as to not expose peoples machines.  Now we want to do the same
thing with solid instead. We want to make these nodes OpenID connect
providers and package it with blockchain and other decentralized
communication, decision support and community governance tools.

In the light of the synereo fiasco
<https://medium.com/@jimscarver/rchain-best-synereo-scenario-it-may-be-a-very-good-time-to-buy-amps-f1ce6e446e11#.wdy2pceld>
moral and enthusiasm of the group has dwindled as the former synereo
community
<https://docs.google.com/document/d/1O_lO6d1uDKRVeCFTg7Tcz0fT6GCqOcoHWEtKga2DDIY/edit>
is morphing into ouRChain.cc <http://ourchain.cc> but there are a few still
active and intreeged by solid but weak in the devops arena. So we would
like to learn collaboratively and hopefully contribute to the project in
building our solid+ network.

To participate email me for a slack invite and DivvyDAO.org has a BYOID
meeting 9am EST Saturdays and community meetings Tuedays 10am EST in the
divvy lobby https://zoom.us/j/6853551826 Free free to join and share solid
stories and help eachother.

I am at step one. I got solid running on windows 10 laptop thanks to help
in gitter <https://gitter.im/solid/chat> and exposed it at
https://fr33id.org:8443/  If you would like to expose your node I can
create an account for you there. I still need to get *.fr33id.org working...

If we can cooperate we can accomplish a lot :-D

Thanks,

Jim
