### ISSUE TITLE
musl dev_t (patch)

### ISSUE THREAD

**Issue by acoul** [solid/solid#129]
the following patch fixes a broken compile on a 32bit alpine-linux

`--- src/solid/devices/backends/udisks2/udisksblock.h.orig
+++ src/solid/devices/backends/udisks2/udisksblock.h
@@ -28,6 +28,10 @@
 #include <sys/types.h>
 #endif
 
+#ifndef __GLIBC__     
+#include <sys/types.h>
+#endif 
+
 namespace Solid
 {
 namespace Backends
`

**Comment by dmitrizagidulin** [comment]
@acoul - do you have the right repo? :) I don't think we have any of this code.

**Comment by acoul** [comment]
you are correct. I apologize.
