### ISSUE TITLE
Port 8443 hardcoded in "select provider" in node-solid-server?

### ISSUE THREAD

**Issue by jakubklimek** [solid/solid#136]
I run node-solid-server at https://solid.opendata.cz, on port 443. When I am at my profile page, i.e. ```https://jakub.solid.opendata.cz/```, and I click on Inbox, it asks me for a Provider (WebID or server URL). When I input https://solid.opendata.cz, it responds with ```request to https://solid.opendata.cz:8443/jwks failed, reason: connect ECONNREFUSED 195.113.18.53:8443```, which seems to indicate that port 8443 is hardwired somewhere.

Here is my ```config.json```
```json
{
  "root": "/data/solid/data",
  "port": "443",
  "serverUri": "https://solid.opendata.cz",
  "webid": true,
  "mount": "/",
  "configPath": "./config",
  "configFile": "./config.json",
  "dbPath": "./.db",
  "sslKey": "./privkey.pem",
  "sslCert": "./fullchain.pem",
  "multiuser": true,
  "corsProxy": "/proxy"
}
```

**Comment by melvincarvalho** [comment]
Although if you're running on https:// without a port that would indicate 443 is successful

- I didnt see 8443 hard coded anywhere 

https://github.com/solid/node-solid-server/search?utf8=%E2%9C%93&q=8443&type=

This is an interesting issue.  I wonder if there's some firewall or reverse proxy on this server.

**Comment by melvincarvalho** [comment]
BTW I made an account and can access : 

https://melvin.solid.opendata.cz/inbox/

and

https://melvin.solid.opendata.cz/public/chat/

in read mode

I was not able to login here, with the error

```
signin.js:732 Uncaught (in promise) TypeError: Cannot read property 'webId' of null
    at signin.js:732
    at <anonymous>
```

Thanks for raising this.  We'll see if we can work it out.  If you have any more insights, or debugging, please add them to this issue.

**Comment by jakubklimek** [comment]
Ahoj @melvincarvalho :)
I did ```solid init```, edited the ```config.json``` so that it looks like what I posted above, and did ```solid start``` (and then ```ctrl+z, bg, disown``` since I ran it from console and I am still only playing around with ```solid```)

**Comment by jakubklimek** [comment]
Actually, that was a second issue I ran into and I am writing down - I cannot login either with WebID-TLS even though I added the certificate info to the WebID and I have the certificate in browser, both in Chrome and Firefox. And it seems to work for http://id.myopenlink.net/ods/webid_demo.html

**Comment by jakubklimek** [comment]
Now I realized that originally, I was running this node-solid-server on port 8443 before switching to 443. So apparently, 8443 got saved/cached somewhere

**Comment by RubenVerborgh** [comment]
It's probably cached in `./db`, can you confirm?

**Comment by dmitrizagidulin** [comment]
Yes, both the server and client configs are cached in ‘.db’, and they contain the ports, and that’s what’s causing the issue. 
So, short term - clear .db dir. 
Longer term - need to open an issue to regenerate the config when the current server url & port does not match the saved config.

**Comment by jakubklimek** [comment]
Confirmed, cleaning the ```./db``` dir solved this.
