### ISSUE TITLE
Wrong tooltip in node-solid-server file browser

### ISSUE THREAD

**Issue by jakubklimek** [solid/solid#140]
In the ```node-solid-server``` file browser, the tooltip for the "Add" button reads:
```Add another tool to the meeting```, but a folder is not a meeting, so something generic like ```Add new object``` is expected:
![image](https://user-images.githubusercontent.com/718827/39928638-367ee7e8-5536-11e8-961d-8b7893ff086c.png)

**Comment by RubenVerborgh** [comment]
Thanks for reporting. That is a Mashlib issue, could you please file it there? https://github.com/linkeddata/mashlib
