### ISSUE TITLE
Have a .well-known route for WebID/TLS to avoid pop-ups

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/solid#145]
There is an ongoing discussion (https://github.com/solid/node-solid-server/issues/672) about how we can have servers that are compatible with both OIDC auth (username/password and WebID-TLS) and WebID-TLS auth on _every_ resource.

For the sake of clarity, let me summarize both options:
- **OIDC auth**
  - can be used with username/password
  - has (only) one WebID/TLS resource, which triggers a client certificate popup through TLS renegotiation
- **WebID-TLS on every resource**
  - asks for a client certificate on every resource as part of the TLS handshake

The tricky question is: **how can we do the convenient (for automated clients) WebID-TLS thing while avoiding its main drawback (horrible browser UI)?**

If we want to avoid the certificate popup on every access, but still want to provide (regular) WebID-TLS auth, we could proceed as follows:
- Have a designated TLS auth resource at a location such as `/.well-known/tls-client-cert`
- This resource triggers a client certificate through renegotiation
- solid-auth-client can be programmed to, in case of a 401 response, send a `POST` request to `/.well-known/tls-client-cert`
- This triggers a client certificate request
- When the client sends a certificate, the server stores the resulting WebID in a cookie
- The client remains authenticated through cookies

An alternative mechanism is that the client adds an HTTP header such as `Client-Certificate: yes` to trigger renegotiation.

**Comment by dmitrizagidulin** [comment]
An excellent suggestion. To implement it, though, we need to make some decisions about the cookie mechanism. Because at the moment, if the app is on an external domain, no cookie will be set.

**Comment by elf-pavlik** [comment]
What advantage do you see in having `/.well-know/tls-clent-cert` and not `Link` header for `rel` like `webid-tls-auth` or something like that?
Does it have to rely on setting a cookie or it could also (or even instead) get a Bearer token after successful authentication with WebID-TLS ?

**Comment by RubenVerborgh** [comment]
> What advantage do you see in having /.well-know/tls-clent-cert and not Link header for rel like webid-tls-auth or something like that?

OIDC also uses a well-known thing, so I wanted to reuse.
Using the rel mechanism might be more complicated with non-200 responses (as a 401/403 would be).

> Does it have to rely on setting a cookie or it could also (or even instead) get a Bearer token after successful authentication with WebID-TLS ?

I'm picking cookie for direct browser support.

**Comment by RubenVerborgh** [comment]
> Does it have to rely on setting a cookie or it could also (or even instead) get a Bearer token

An actually, that would just be OIDC then.

…which is the other option that would make this issue unnecessary, i.e., just go through the OIDC process, use a client cert for that, and then Bearer token from there.

**Comment by RubenVerborgh** [comment]
> If you establish cookie sessions

Honestly, I'm not a fan of the session cookies we currently have; they are opaque identifiers the client cannot use.
I'd like to replace them with cookies that a client can read, so it at least understands what going on. E.g., something like "signed on to X as Y" (accompanied by a cryptographic hash so the server can verify authenticity). This also saves the server from keeping state.

> and then you want to use different identity, you would need to somehow re-establish a new cookie session with each of the servers.

That's solvable, especially with transparent cookies.

**Comment by melvincarvalho** [comment]
> how can we do the convenient (for automated clients) WebID-TLS thing while avoiding its main drawback (horrible browser UI)

Do automated clients such as curl send the Origin header?

If not, you could perhaps say, if there's no origin header accept a client certificate.

**Comment by RubenVerborgh** [comment]
> Do automated clients such as curl send the Origin header?

Not by default.

> If not, you could perhaps say, if there's no origin header accept a client certificate.

That's actually a sweet idea.
But we'd need to refine, as Origin is only set for AJAX requests.

**Comment by elf-pavlik** [comment]
> An excellent suggestion. To implement it, though, we need to make some decisions about the cookie mechanism. Because at the moment, if the app is on an external domain, no cookie will be set.

When it comes to cookies do we have to keep user consent in mind? https://www.cookiebot.com/en/cookie-consent/

**Comment by RubenVerborgh** [comment]
Fortunately not: it's an essential cookie for auth, not for tracking.
