### ISSUE TITLE
Explain students about your project/get students involved

### ISSUE THREAD

**Issue by orishahori** [solid/solid#150]
Hi, I'm a teacher from Israel, and would like to introduce the Solid project to my students. I think I can mannage with explaining what you are doing, even though I am not a Tech person. I'm a history teacher. However I want to get them involved in this. How can I do that? Or- Do you have maybe people in Israel who can guide us?
Thanks so much.
Cheers,
Ori.

**Comment by bblfish** [comment]
It looks like you need a high level overview. That is why I wrote up a paper called "[Epistemology in the Cloud - On Fake News And Digital Sovereignty](https://medium.com/@bblfish/epistemology-in-the-cloud-472fad4c8282)" which has been peer reviewed. That and articles linked to from there can give you a poltical/technical understanding of why it is important.

**Comment by orishahori** [comment]
Thank you so much!

**Comment by RubenVerborgh** [comment]
@orishahori In case this helps with your explanation, here is a layman's version:

https://www.quora.com/In-laymans-terms-what-is-the-essence-of-Sir-Tim-Berners-Lees-project-Solid/answer/Ruben-Verborgh

But your question was about getting involved. I would say the main starting place is the Gitter channel: https://gitter.im/solid/chat We hang out there to help newcomers and direct them.

A good starting point is the Solid website: https://solid.mit.edu/ There are some pointers on there right now, but the website will get a major overhaul in about 2 weeks to contain lots of helpful resources.

**Comment by orishahori** [comment]
Thanks so much!

**Comment by RubenVerborgh** [comment]
Feel free to ask for more!
