### ISSUE TITLE
How to wrtite solid-client apps for WebID and resources on "solid.community" server?

### ISSUE THREAD

**Issue by bellbind** [solid/solid#151]
Hi, I started to learn technologies of the solid. 
I registered as `https://bellbind.solid.community/` to play, run local [node-solid-server](https://github.com/solid/node-solid-server/) to know internal data contained, and then I read the specs of [Linked-Data Platform](https://www.w3.org/TR/ldp/) and [WebID-TLS](https://dvcs.w3.org/hg/WebID/raw-file/tip/spec/tls-respec.html).

On following step, I tried to write the solid apps to remotely access resources on solid servers by [solid-tutorial-intro](https://github.com/solid/solid-tutorial-intro/) and [solid-client](https://github.com/solid/solid-client/).
Everytimes I failed trying to use both resources and WebIDs on **solid.community** or **solidtest.space**.

The [solid-tutorial-pastebin](https://github.com/solid/solid-tutorial-pastebin/) mentions the "databox.me" URL.
Finally I could write apps to **access resources on "databox.me" with WebIDs on "databox.me"** because I could register accounts on "databox.me" from hidden pages.
But the `https://databox.me/` says **begin retired** and has no links to registration pages.

---

So I have several basic questions:

- What is the "databox.me" server?
  The URL of "databox.me" is coded in `config-default.json` files in the "solid-client" and
  its dependent libraries (e.g. [solid-auth-tls](https://github.com/solid/solid-auth-tls)).
- Why cannot the `SolidClient` access resources and WebIDs on "solid.community" and "solidtest.space"  with same scripts? (or `SolidClient.signin()` works with no configs?)
  Is some additional snippet required in client scripts?
  Or, are the libraries not supported to access other than "databox.me" servers yet?
- Do any extra limitations exist on "solid.community" and "solidtest.space"? (e.g. app URL limitations)
- Is it valid behavior that `SolidClient.currentUser()` always returns `""` with WebID on "databox.me"?
  The XHR response log on webconsole seems to hold the databox.me WebID.

---

There are my trial app scripts on gist:

- [using currentUser/login/signup then recursive traverse resources](https://gist.github.com/bellbind/c5c2d3e57818686e8d7e7e7056d3fb9e)
- [pastebins app from scratch](https://gist.github.com/bellbind/7cf6dce4dc45f18ae4a05a472c388b29)

These scripts only depend on the `solid-client` library bundle at https://solid.github.io/releases/ .

I open and reload these `index.html` files with browsers via `http://localhost:8000/` from `python3 -m http.server`.
These browsers are firefox-62 and chrome-71 on macOS-10.13.6 (with no private browsing modes and removed all serviceworkers).
And everytime before opening `index.html` with WebID such as `https://bellbind.databox.me/profile/card#me`, I do login at `https://bellbind.databox.me/` on other tabs of same browser.

**Comment by RubenVerborgh** [comment]
Hi @bellbind ,

> On following step, I tried to write the solid apps to remotely access resources on solid servers by [solid-tutorial-intro](https://github.com/solid/solid-tutorial-intro/) and [solid-client](https://github.com/solid/solid-client/).

These are unfortunately a bit outdated. We should add labels to them.

> Everytimes I failed trying to use both resources and WebIDs on **solid.community** or **solidtest.space**.

Yes. You need solid-auth-client to work with these, that's our latest auth library.

>     * What is the "databox.me" server?

An old server running https://github.com/linkeddata/gold

>       The URL of "databox.me" is coded in `config-default.json` files in the "solid-client" and

Indeed; that repository is deprecated.



If you want to start developing for the current node-solid-server, I recommend:
- https://github.com/solid/solid-auth-client (for authenticated resource access)
- https://github.com/solid/query-ldflex/ (<= exciting new library for accessing data)

**Comment by bellbind** [comment]
I write a tiny example for solid-auth-client on browser. It works my WebIDs on solid.comunity and solidtest.space .

- https://gist.github.com/bellbind/eb00a346d763b711d9f959ac3a8b715c

When `solid.auth.popupLogin({popupUri})` executed,  it opens `https://solid.community/common/popup.html`. 
Choosing "Log in with custom provider", its input **placeholder displays `https://my-identity.databox.me/profile/card#me`**. 

I tried to use my `https://bellbind.databox.me/profile/card#me` for "Log in".
But Web console reported as:

```
GET
https://bellbind.databox.me/.well-known/openid-configuration#me
[HTTP/2.0 404 Not Found 858ms]

Error logging in with WebID-OIDC popup.html:17:40659
Error: "Error fetching openid configuration: 404 Not Found"
exports https://solid.community/common/popup.html:24:8497 popup.html:17:40708 
```

The old "databox.me" seems incompatible with solid-auth-client because of no WebID-OIDC features.  
Is WebID-TLS also deprecated as solid system? or not implemented yet?

**Comment by melvincarvalho** [comment]
Correction : Actually I just learnt that node-solid-server running in TLS mode doesnt have delegated hand off.  So optimal is to run in oidc mode right now (the default).  Hopefully we can document what this means a bit better with the newest version.

**Comment by RubenVerborgh** [comment]
@bellbind Did you try it with solid.community as your provider? That server is compatible with OIDC and thus solid-auth-client.

**Comment by bellbind** [comment]
Thank you @melvincarvalho .

In my understanding, solid-auth-client is already implemented both WebID-TLS and WebID-OIDC and their hand-off, but there are some problems in server-side programs as:

|host|program|WebID-TLS|WebID-OIDC|OIDC<=>TLS hand-off|
|------|----|----------|----------|------------------|
|solid.community|node-solid-server|option|default|implementation bug?|
|databox.me|gold|default|not existed|not existed|

Is it OK?

**Comment by RubenVerborgh** [comment]
Okay, except that it's not an implementation bug but an impossibility. TLS does not offer hand-off. solid-auth-client is OIDC-only.

**Comment by bellbind** [comment]
> @bellbind Did you try it with solid.community as your provider? That server is compatible with OIDC and thus solid-auth-client.

Yes, it works with WebIDs on both solid.community and solidtest.space. 

I tried to check all 3 buttons on the popup window. But the case of **"Log in with custom provider" with a WebID on databox.me** is failed. (A case of "Log in with custom provider" with a WebID on solid.community or solidtest.space is success).

**Comment by RubenVerborgh** [comment]
> But the case of **"Log in with custom provider" with a WebID on databox.me** is failed.

That is expected behavior indeed; solid-auth-client only supports OIDC servers.

**Comment by bellbind** [comment]
OK, I understand it is valid that solid-auth-client apps fail  to use databox.me WebIDs.

As a specification of solid, both WebID-TLS and WebID-OIDC may exist. 
Server-side implementations supports some of these authentication methods.
But as a client-side, WebID-OIDC client may have some difficulties of WebID-TLS client as a option.

**Comment by melvincarvalho** [comment]
> As a specification of solid, both WebID-TLS and WebID-OIDC may exist.

Correct!

> Server-side implementations supports some of these authentication methods.

Also correct!

> But as a client-side, WebID-OIDC client may have some difficulties of WebID-TLS client as a option.

I didnt know this.  But I would think that client side should ideally work with both?   @RubenVerborgh may have a better answer here.

**Comment by RubenVerborgh** [comment]
> But as a client-side, WebID-OIDC client may have some difficulties of WebID-TLS client as a option.

A WebID-OIDC client simply does not support WebID-TLS.

The issue with WebID-TLS with regard to a client, is that the TLS part is handled by the browser itself. The client doesn't really have much of a say in this.

**Comment by melvincarvalho** [comment]
It is true that, WebID-TLS is handled by the chrome of the user agent (browser).  And that the chrome is outside of control of a javascript client.

However, this is true of many APIs on the web platform (e.g. such as webcrypto).  What can be helpful is a wrapper around chrome specific APIs.

**Comment by RubenVerborgh** [comment]
Yes, but the difference is that the TLS stuff isn't exposed as an API currently.

**Comment by melvincarvalho** [comment]
Indeed, it's not an API.  But it can be wrapped, then it becomes an API.

**Comment by melvincarvalho** [comment]
You do a fetch to a known endpoint (which could be a random choice from one of many, or even your own pod), and you get get back either an authenticated user, or a failed state.

**Comment by RubenVerborgh** [comment]
> You do a fetch to a known endpoint (which could be a random choice from one of many, or even your own pod), and you get back either an authenticated user,

Makes sense, but note that technically, this isn't enough, because a user might be logged in with one server but not with another, or even with different users on different servers.

So the problem of it being browser-driven, and a main reason why we need to drop WebID-TLS support from solid-auth-client, is that we cannot say "you are logged in as X", as we can for WebID-OIDC. Rather, we would have to say (in theory) "you are logged in as X on S1 and as on S2" and we could only find that out by exhaustively trying all Sx for that.

The main difference between WebID-TLS and WebID-OIDC is this consistency and control that a JavaScript client has, which becomes especially difficult the moment we start accessing more and more servers (as we will eventually need to in decentralized apps).

**Comment by melvincarvalho** [comment]
> Makes sense, but note that technically, this isn't enough, because a user might be logged in with one server but not with another, or even with different users on different servers.

RDFlib records this

> So the problem of it being browser-driven, and a main reason why we needed to drop WebID-TLS support from solid-auth-client, is that we cannot say "you are logged in as X", as we can for WebID-OIDC. 

I see where you're coming from, tho it's an edge case.  For example, has any user ever reported this?  Meanwhile users report not being able to log in with WebID-TLS all the time (see this issue!).

> Rather, we would have to say (in theory) "you are logged in as X on S1 and as Y on S2" and we could only find that out by exhaustively trying all Sx.

I see the problem, it makes sense, tho again an edge case.  I dont have a solution off the top of my head.  Good to record this!

> The main difference between WebID-TLS and WebID-OIDC is this consistency and control that a JavaScript client has, which becomes especially difficult the moment we start accessing more and more servers (as we will eventually need to in decentralized apps).

Got it.  So the question remains what is the best way for user log in via WebID-TLS to a WebID-TLS sever, which is the pattern that has driven solid for 5+ years.  Use another library?  Write inline code?  Write a wrapper around solid-auth-client or add a helper.  

Reto wrote a nice util library that does this : 

https://github.com/retog/solid-utils#solid-utils

Perhaps the way forward?

**Comment by RubenVerborgh** [comment]
> I see where you're coming from, tho it's an edge case.

Edge case indeed, but it has major architectural consequences. All current Solid client software assumes that the user is logged in with one WebID.

And the problem is not so much that this situation can arise, but that no client library can fix it for the user. They literally have to restart the browser or install OpenLink's extension.

> For example, has any user ever reported this?

No, because we don't have may cross-pod apps yet. Chicken and egg though.

My case of multiple pods is an edge case now, but if we want to use Solid for social feeds (or any other application that uses multiple people's data), we will easily run into this.

> Meanwhile users report not being able to log in with WebID-TLS all the time

Yeah we need to document that better. solid-auth-client only supports WebID-OIDC (despite the initial goals of the library).

> Got it. So the question remains what is the best way for user log in via WebID-TLS to a WebID-TLS sever

One server is fine, we got that. The problem of how to guarantee a single WebID login to all accessed pods is not solvable without extending the browser. There is simply no hand-off in the WebID-TLS protocol, so the initial goal of solid-auth-client to make a uniform solution was impossible technically.

> Reto wrote a nice util library that solid-auth-client :
> 
> [retog/solid-utils#solid-utils](https://github.com/retog/solid-utils#solid-utils)
> 
> Perhaps the way forward?

Not for this auth issue unfortunately, as it just reuses the client.

**Comment by melvincarvalho** [comment]
> Edge case indeed, but it has major architectural consequences. All current Solid client software assumes that the user is logged in with one WebID.

This needs to be documented better.  What does current mean in this context?  Can you log in as different WebIDs from different origina?  In different windows (im thinking incognito windows that dont require a restart)?  Let's nail down what's being said here.  Something like "solid auth client assumes a single WebID for a given origin, in a given browser session" -- something like this.  WebID-OIDC was proposed to run alongside WebID-TLS, not to replace it.  So there's going to be push back if that is changed.

**Comment by RubenVerborgh** [comment]
@melvincarvalho Let's follow up in #152 to give poor @bellbind a break :-)

@bellbind Let us know how we can help you.
