### ISSUE TITLE
WebID-TLS: API mismatch between libraries and browser

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/solid#153]
### Background
It has been a design goal to run WebID-OIDC _alongside_ WebID-TLS (#22). This means that we need client libraries that abstract away the differences between the two. This issue argues why the current abstraction we use is inadequate.

### Summary
Current client-side browser libraries for Solid are incompatible with the browser model for TLS with client certificates. Those libraries assume that `currentUser` is a function of the application, whereas it actually is a function of the request origin and destination origin. Furthermore, the client-side library has no control over the value of that function. As a result, the used abstraction does not accurately represent reality.

### Consequences
Because of their API, current client-side libraries cannot accurately represent or manipulate user authentication status with WebID-TLS. This is not an implementation problem, but a design problem.

### Intended usage
User _U_ wants to use one of their WebIDs _W1_, _W2_, …, _Wk_ to sign in to an application _A_ running on a data pod _Pa_ in order for that application to be able to access data from pods _P1_, _P2_, …, _Pn_.

Currently, applications typically require data from a relatively low number of pods. However, as more users join Solid and store data in their own pod, it will not be unusual for an application to access tens or hundreds of pods (use case: a social media feed of all your friends).

### Current TLS client certificate implementation in browsers
In current browsers, the client certificate—and thus, for Solid purposes, their WebID—is a function of request origin and destination origin (where "origin" = "host:port").
In other words:
```
TlsUser := f(requestOrigin, destinationOrigin) = webID
```

### OIDC functionality
With OIDC, the client identity—and thus, for Solid purposes, their WebID—is a function of the current application. (In the Solid implementation, of the current origin, but that is a changeable implementation detail.)
In other words:
```
OidcUser := f(currentApplication) = webID
```

### Current client-side library API
Current libraries, including rdflib, solid-client, and solid-auth-client, expose (in one way or another) a `currentUser()` function that returns the currently logged in user to the application.
In other words:
```
LibraryUser := f(currentApplication) = webID
```
Here, `currentApplication` is an implicit parameter that is not explicitly passed to the function, but derived by the library from the execution context.

### Issue with current client-side API
As we can see from the above definitions, there is a match between `LibraryUser` and `OidcUser`, but a mismatch between `LibraryUser` and `TlsUser`. This means that no current library accurately captures the TLS authentication status, not because of an implementation issue but because the API is incorrect.

In other words, current libraries expose a function to answer the question "Who is logged in to the application?", but this question is not meaningfully defined for TLS in the browser. It is as if someone where to ask another person the question "what number do you have?": we cannot meaningfully give an answer, because we lack context parameters to determine whether this is a street number, office number, phone number, or something else.

In TLS, there is only a meaningful answer to "which user identity will be used to fetch data for host X to host Y", and that answer would vary with different values of X and Y.

### Why did it work then?
Several people have been successfully using WebID-TLS, also through some of the aforementioned libraries. So why did this work while we just have shown that it could not have?

The answer is in our definition above:

> User _U_ wants to use one of their WebIDs _W1_, _W2_, …, _Wk_ to sign in to an application _A_ running on a data pod _Pa_ in order for that application to be able to access data from pods _P1_, _P2_, …, _Pn_.

In _current_ Solid applications, it very often happens that _Pa=P1=Pn_. That is: the application is on the same domain as the data, and most authenticated data comes from that one location.

In other words, while `TlsUser` and `LibraryUser` above tell us that:
```
f(A) = webID1         # LibraryUser
f(Pa, Pa) = webID2    # OidcUser
f(Pa, P1) = webID2    # OidcUser
…
f(Pa, Pn) = webIDn+1  # OidcUser
```
and hence there are _n + 1_ possible definitions of `currentUser` for application _A_.

Yet in practice, we had:

```
f(A) := f(Pa, Pa = P1 = Pn) = webID1
```
so that it was simply assumed that `currentUser` was equal to whichever webID would fetch data from `f(Pa, Pa)`.

As an example, Melvin would go to timbl.com, authenticate as `f(timbl.com, timbl.com) = webIDmelvin`  and be served the databrowser's chat pane, which would read its data from timbl.com and also store it there. Therefore, there seemed to be no question that `currentUser = webIDmelvin` and we would say that "Melvin is logged in as webIDmelvin to the databrowser on timbl.com". However, reality is only reflected in the statement that "Melvin's browser uses webIDmelvin to fetch data for timbl.com from timbl.com".

### Why will we notice in the future that this API abstraction is broken?
Given that, in the Solid vision, every person should be able to store data where they want, we assume that people will be able to store every single piece of data they produce. As argued [here](https://ruben.verborgh.org/blog/2017/12/20/paradigm-shifts-for-the-decentralized-web/#users-become-owners-p-5), this means that every small piece of data, such as every individual like on a post, could be stored in another place. So when generating a social media feed in the Solid ecosystem, it is not unrealistic that tens or hundreds of pods will need to be queried.

As an example, rather than storing every message of a timbl.com chat on timbl.com (as we do today), every user could store their own messages on their own pod (and post links to them on the timbl.com chat).

This means that the function `currentUser()` suddenly becomes ill-defined. Because where do we look to determine that information? `TlsUser` is not defined in terms of an application, but in terms of request and destination origins. In other words, the API cannot be:
```
currentUser([implicit]application)
```
but should rather be
```
currentUser([implicit]applicationHost, datapod)
```

Now of course we could argue that "users will always use the same WebID to sign in to all of the data pods they access", but that is not the point. The point is that the browser is imposing this API on us because of the way the UX is designed, and that we cannot change that contract (unless we change the browser).

### Control over the value of the function
Another major difference is that, with WebID-TLS, the value of `TlsUser` is set by the browser (through a user interaction) and cannot be changed without restarting the browser (unless through an extension, but even then possibilities are limited).

With WebID-OIDC, the value of `OidcUser` is set by the client-side library in JavaScript (through a user interaction), and can be changed.

This means that, for WebID-TLS, the functions `login()` and `logout()` are essentially meaningless (without browser extension, which is again limited).

### Impact
This issue has already had impact: because the `TlsUser` function was assumed to be the same as `LibraryUser`, solid-auth-client would assume you were "logged in to the application" as soon as the user authenticated with WebID-TLS to one host. This is reflected in the API design, which has a `currentSession()` function. However, this assumption is incorrect, as proven above: there is no such thing as logging in to an application with WebID-TLs. This misconception resulted in the UI displaying "logged in as X" while requests to a server would fail with a 401 status code (https://github.com/solid/solid/issues/138#issuecomment-387439471). Furthermore, since the client is not in control over those values, we cannot transfer a login from one server to another (as we can with OIDC). The library assumed—as any other library with the same API—that the identity was tied to the application, whereas it is not.

### Conclusion
Client-side libraries cannot use `currentUser()`, `login()`, `logout()` contracts for WebID-TLS. The proper contract for the first is `currentUser(datapod)`, and `login` and `logout` have no meaningful interpretation. Hence, creating an abstraction for running WebID-OIDC _alongside_ WebID-TLS is not possible with this API.

Either the API has to change, which might be inconvenient, or browser functionality needs to be altered through source code modifications and/or extensions, which might make adoption difficult.

Alternatively, we can redefine "alongside". For instance, by picking OIDC as main authentication protocol, but still allowing users to identify themselves to OIDC through a client certificate. This latter behavior is provided by node-solid-server in OIDC mode.

**Comment by kjetilk** [comment]
OK, what can I say but *wow*...?

Anyway, a short interjection here: I've had it on my whiteboard since a conversation I had with @theWebalyst et al that we also in practice have WebID-SAFE now, and so, we should see if we can have an API that can scale to other authentication schemes as well.

**Comment by melvincarvalho** [comment]
Thanks for writing this up!

Short version for now : 

Starting from function

`f(origin, destination)`

We wanted to create a new matching function.  But we created

`f(origin)`

In all practical cases, that I know of

`f(origin, destination) = f(origin)`

So the obvious solution : 

Just set the new interface to be 

`f(origin, origin)`

Alternatively, change the old interface to match the new (dangerous, but I think OK in this case)

`f(origin)`

The temporal aspect adds a slight complexity.

But in a nutshell, I think this can be fixed by saying that the logged in user with WebID-TLS is the *most recent* user that you are seen to log in as.  In 99% of cases this will work the same.  The strange edge case is where you choose different webids for different servers in the same tab.  We can say that this gives unexpected results -- however probably not all that unexpected to the any user that would so something so weird! :)

**Comment by RubenVerborgh** [comment]
Just set the new interface to be

f(origin, origin)

But that's the thing, you can't unilaterally decide that. The browser decides this for us.

Alternatively, change the old interface to match the new (dangerous, but I think OK in this case)

f(origin)

I wouldn't call it dangerous (semver major), just hideous 😉


But in a nutshell, I think this can be fixed by saying that the logged in user with WebID-TLS is the most recent user that you are seen to log in as.

So as per the above, there is no concept of "logged in", only "fetch for this host from this host as X.

Assuming we mean that, questions:
- If the client sees 99 fetches as X and one last one as Y, the user is Y?
- If the client sees 99 fetches as X and one last one as none, the user is logged out?

In 99% of cases this will work the same. The strange edge case is where you choose different webids for different servers in the same tab.

Or click cancel one time.

In all practical cases, that I know of

Do you agree with my assessment that we have mainly focused on single-server apps (wrt private resource access), and that this is likely to evolve in the future?
(This also relates to other things that are not an issue in single-server but would be in multi, like the many modals.)

**Comment by melvincarvalho** [comment]
@RubenVerborgh thanks for the comments.  Will digest!

Just on : 

> Do you agree with my assessment that we have mainly focused on single-server apps (wrt private resource access), and that this is likely to evolve in the future?

I certainly have not done this.  I always pulled in resources from multiple locations, including localhost, and mashed them together.  For me, that's the fun of solid.  However, my usage is probably different (dare I say more advanced?) than most others.

What I always did was use the same webid for each origin.  I think that's the obvious thing to do.  I'm scratching my head to think why anyone would ever do otherwise.  For anyone crazy enough to want to do thatthat, I think the principle of [caveat emptor](https://www.merriam-webster.com/dictionary/caveat%20emptor) is implied!

**Comment by RubenVerborgh** [comment]
I certainly have not done this. I always pulled in resources from multiple locations, including localhost, and mashed them together.

Interesting! For my understanding, what would be a typical number of sources in your cases? Would you expect rust number to grow? And if that number is (let's say) 10, would you get 10 certificate selection prompts?

Are those pods from different people or all yours? If all yours, what is the reason for splitting, and how do you choose what data to put where?

Apologies for the many questions and thanks in advance for your insights 🙂

**Comment by kjetilk** [comment]
> What I always did was use the same webid for each origin. I think that's the obvious thing to do. I'm scratching my head to think why anyone would ever do otherwise. 

I'm also scratching my head. Possibly scratching my head sufficiently to run into the absurd that we shouldn't optimize for ;-) , but...:

A WebID may in itself be sensitive personal information, by e.g. GDPR and others. So, we might run into a situation where you might integrate data using both a "casual" WebID that you use in public with no expectation of privacy, and a sensitive one... Like the SciAm 2001 usecase of finding a doctor, and drive there with a ridesharing app... Would that be relevant?

**Comment by elf-pavlik** [comment]
> Would you expect rust number to grow? And if that number is (let's say) 10, would you get 10 certificate selection prompts?

I might have missed something but last time I recall looking at this issue it seemed not to have a solution which would prevent browser prompting for certificate unless the client itself chooses to initiate WebID-TLS flow. That seems to result in situation where anyone who has at least one certificate installed in web browser, and have done it for non Solid related purposes, will keep getting an avalanche of cert selection pop-ups even if the person always wants to use WebID-OIDC when using Solid platform. This sounds to me like an awful UX limbo.

> Alternatively, we can redefine "alongside". For instance, by picking OIDC as main authentication protocol, but still allowing users to identify themselves to OIDC through a client certificate. This latter behavior is provided by node-solid-server in OIDC mode.

I have impression that this conversation spans over many different github issues. Most recently this one and #152 but it appears more and more that WebID-TLS simply can't smoothly run alongside WebID-OIDC. I see proposed redefinition of "alongside" as unavoidable. Stronger separation between IDP services and dataset services may help to draw further distinction between plenitude of mechanisms which different IDP services may choose to offer for authenticating onself with IDP vs. minimum common mechanism which all apps and dataset services will have to rely on when enforcing ACL rules and this way stay interoperable.

Please excuse me if I distract from very specific topic of this issue, if this broader conversation should happen in another issue I can delete this comment here and re-post based on your suggestion.

**Comment by Mitzi-Laszlo** [comment]
You can find more conversation on this subject here https://forum.solidproject.org/t/webid-tls-api-mismatch-between-libraries-and-browser/398
