### ISSUE TITLE
Can't access Friends app

### ISSUE THREAD

**Issue by tuukka** [solid/solid#155]
1. I log in at inrupt.net and there's a prominent link to https://databox.me/apps/friends/
2. The Friends app says "Let's get you connected!" and I click "I use Solid"
3. Under "Sign in with your WebID account", I enter my inrupt.net subdomain.

Expected result: I'm logged in and see the Friends app.

Actual result: Nothing happens. In the browser console, I can see an error: `TypeError: rels['http://www.w3.org/ns/solid/terms#proxyEndpoint'] is undefined`

**Comment by RubenVerborgh** [comment]
Hi @tuukka,

Thanks for getting in touch he Friends app only supports one authentication mechanism, whereas inrupt.net uses another. We need to update the Friends app to work with our newer authentication stack.

I'll make sure that the Friends app isn't displayed until we got this fixed.

Ruben
