### ISSUE TITLE
Serve Solid favicon.ico if they don't exist

### ISSUE THREAD

**Issue by nicola** [solid/solid#16]
To avoid serving 404

**Comment by ebporter** [comment]
Here's how I think we should use favicons in the Solid ecosystem:
* The Solid server comes with a Solid favicon by default, and it appears if no other favicon is specified.
* The Solid server service provider can override the default Solid favicon with their own icon.
* The end user can override the service providers favicon with their own icon.
* An app provider can override the end user's favicon with their own icon.

**Comment by dmitrizagidulin** [comment]
Implemented in [`node-solid-server` PR #481](https://github.com/solid/node-solid-server/pull/481).
Currently shipping a default `favicon.ico` in the `static/` directory of the node-solid-server repo.
Service providers can either override it, or use the usual html `<link>` mechanism to point to a different one.
Closing this issue.
