### ISSUE TITLE
signup form is missing password strength indication

### ISSUE THREAD

**Issue by stuartyeates** [solid/solid#163]
The signup for needs to password strength indication, operating in either inforcing or educational mode. 

Something like: https://github.com/nowsecure/owasp-password-strength-test https://www.npmjs.com/package/password-strength-meter

**Comment by mintunitish** [comment]
Can I take up this issue?

**Comment by mintunitish** [comment]
i would like to take it!

**Comment by kjetilk** [comment]
BTW, please branch off of the `develop` branch. :-)

**Comment by kjetilk** [comment]
BTW, it would be really nice to have support for the list of breached passwords at https://www.troyhunt.com/ive-just-launched-pwned-passwords-version-2/#cloudflareprivacyandkanonymity

**Comment by mintunitish** [comment]
So I will be putting the check against owasp specs and breached passwords.

**Comment by mintunitish** [comment]
Submitted the [PR](https://github.com/solid/node-solid-server/pull/845)

**Comment by mintunitish** [comment]
I think this issue can be closed now!
