### ISSUE TITLE
WebID validation is missing

### ISSUE THREAD

**Issue by Vanuan** [solid/solid#164]
Registration page doesn't explain what is WebID and doesn't have any validations on it. It means that you can register with invalid WebID which you would not be able to change.

**Comment by megoth** [comment]
We think this has been fixed in https://github.com/solid/node-solid-server/pull/818, but please let us know if you think this issue persists.

I'll close this issue for now.

**Comment by Vanuan** [comment]
It there a way to delete account and register it again?

**Comment by megoth** [comment]
@Vanuan there's a thread on how you can delete your account ^_^ https://forum.solidproject.org/t/how-can-i-delete-my-account-on-a-solid-pod-provider/25/2
