### ISSUE TITLE
Errors in accessing my new account

### ISSUE THREAD

**Issue by pcav** [solid/solid#165]
I keep on getting:
`Outline.expand: Unable to fetch <https://pcav.solid.community/inbox/>: Failed to load  <https://pcav.solid.community/inbox/> Fetcher: <https://pcav.solid.community/inbox/> Unauthorized status: 401`
I don't know if related, I'm also getting `Error: undefined` when editing my profile https://pcav.solid.community/inbox/
Thanks

**Comment by ajspadial** [comment]
Same happens to me. I want to edit my account in order to modidy my WebID URL. I introduced a wrong one when I registered myself.

**Comment by RubenVerborgh** [comment]
All 3 browsers? This is new, thanks for letting us know. Hope I can reproduce it; I have seen some people get it when following steps during a tutorial, but the majority never gets it. There must be a small difference somewhere.

**Comment by piecurus** [comment]
I'm on macOS though

**Comment by RubenVerborgh** [comment]
Same.

**Comment by kjetilk** [comment]
Strange! By accessing the resource in #206 it seems that these files have been corrupted by an editing step, so we need to dig deeper. We should have validation of any input before writes are done. 

Are any of you able to describe any editing steps you did before you saw this error?

**Comment by piecurus** [comment]
It happened several times. For example, when trying to modify the content of "my card" or creating a new folder

**Comment by melvincarvalho** [comment]
```
@prefix solid: <http://www.w3.org/ns/solid/terms#>.
@prefix foaf: <http://xmlns.com/foaf/0.1/>.
@prefix pim: <http://www.w3.org/ns/pim/space#>.
@prefix schema: <http://schema.org/>.
@prefix ldp: <http://www.w3.org/ns/ldp#>.

<>
    a foaf:PersonalProfileDocument ;
    foaf:maker <https://test.solid.community/profile/card#me> ;
    foaf:primaryTopic <https://test.solid.community/profile/card#me> .

<https://test.solid.community/profile/card#me>
    a foaf:Person ;
    a schema:Person ;

    foaf:name "test" ;

    solid:account </> ;  # link to the account uri
    pim:storage </> ;    # root storage

    ldp:inbox </inbox/> ;

    pim:preferencesFile </settings/prefs.ttl> ;  # private settings/preferences
    solid:publicTypeIndex </settings/publicTypeIndex.ttl> ;
    solid:privateTypeIndex </settings/privateTypeIndex.ttl> .
```

Here is a test profile *template* to show what it should look like.  It may be possible to undo the edit.

**Comment by melvincarvalho** [comment]
Notes on above : 

- the only thing needed to change is `foaf:name`
- there are 3 absolute links in the profile
- relative links there would enable easier recovery, and more portability

**Comment by megoth** [comment]
I'll close this issue for now, but please reopen it if this continues to happen. If you're able to provide a list of steps to reproduce it, that would be great! =)

**Comment by NMITTutor** [comment]
<https://jsndrop.com:8443/inbox/>: Failed to load , I think I need to reinstall ??
