### ISSUE TITLE
Unable to delete account

### ISSUE THREAD

**Issue by scottybo** [solid/solid#166]
You guys talk about GDPR compliance as a big selling point, yet I'm unable to delete my account on Solid Community.

Please advise how I may delete my account.

**Comment by RubenVerborgh** [comment]
> You guys talk about GDPR compliance as a big selling point

Could you point us to the source of that info? Just want to make sure that it is communicated right.

> Please advise how I may delete my account.

Please mail admin+security@inrupt.com and we'll help you right away.

**Comment by scottybo** [comment]
Ah, seems that it was just mentioned in the Product Hunt submission by someone not in your project. My bad.

Still you need to make sure that it's possible to to delete an account.

**Comment by kjetilk** [comment]
Yeah, we got it prioritized now: https://github.com/solid/node-solid-server/issues/177
Sorry it wasn't there from the start.
