### ISSUE TITLE
encrypted POD?

### ISSUE THREAD

**Issue by taggart** [solid/solid#170]
My organization has several applications that might be interesting candidates to move to solid. We currently store the application data on our own backends, but we could potentially become a POD provider and allow our users to use us or another provider instead. One of our requirements for doing so would be to have a way that data on the POD provider is encrypted in a way that the POD provider itself cannot read. Or maybe put in more generic terms, access control should be cryptographically ensured.

Some of the reasons for doing this include:
* organized crime, nation-state, etc hacking of services to steal user data
* data breach through misconfiguation, API bugs, etc
* physical theft of equipment
* see https://haveibeenpwned.com/
* malicious POD providers monetizing user data, injecting ads/malware/etc

The best way to protect the users is for the POD provider to not have access to the data.
Is solid designed with this in mind? If not, would it be possible to add?

Thanks

**Comment by panleya** [comment]
www.proxycard.io has a technology that might be useful.  Essentially every user is granted their own personal SSL certificate, with the private key broken into two parts.  The first is stored behind a login and the second on a physical NFC card or stored on their phones.

**Comment by tatwater** [comment]
I think ensuring the data store is encrypted would be a very welcome or even necessary feature for a large number of potential applications, and could also be a compelling argument for consumers to trust and adopt Solid more quickly!

**Comment by kjetilk** [comment]
I have now finally gotten around to write a bit about this over in the Solid forums:
https://forum.solidproject.org/t/encrypted-pod-is-solid-designed-with-this-in-mind-if-not-would-it-be-possible-to-add/399

We are trying to migrate discussion and questions over there, so please continue in that thread!

**Comment by csarven** [comment]
@kjetilk Who is "we"? Can you clarify what you (the "we") think the GitHub issues for this repository is intended for? Is this documented (URL)?

**Comment by kjetilk** [comment]
@csarven , yeah, we are us inrupters. :-) We hope to make the whole process more manageable by providing a Discourse forum for discussion.

**Comment by csarven** [comment]
Replied at https://gitter.im/solid/chat?at=5be2f4407a36913a9a064514 since we are already off topic :)
