### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by oshihirii** [solid/solid#171]
Just detailing my experience as new user.

Environment:
Chrome 69.0.3497.105
IPad Model MP2G2X/A

Steps to recreate:

I registered a pod here:

https://inrupt.net/

I login here:

https://inrupt.net/login?

I am shown a ‘public homepage’ which is a bit alarming, because I didn’t want/wasn’t told I would have a public homepage that used my username.

https://my-username-here.inrupt.net

It has a login button at the top.  

When I click on that it opens a new tab at:

https://my-username-here.inrupt.net/common/popup.html

with 4 login options.  

When I click on the option:

‘Login with my-username-here.inrupt.net’ 

nothing happens.

**Comment by kjetilk** [comment]
By "nothing", you mean that the button doesn't seem to respond? If so, I've seen that myself, but I haven't been able to debug.

And yeah, we need to explain that the username is public: https://github.com/solid/node-solid-server/issues/823

**Comment by kjetilk** [comment]
I just looked something more into this, and what I'm getting on the console is this:

```
Error logging in with WebID-OIDC
popup.html:24:102872
TypeError
​
columnNumber: 0
​
fileName: ""
​
lineNumber: 0
​
message: "NetworkError when attempting to fetch resource."
​
stack: ""
​
__proto__: Object { stack: "", … }
popup.html:24:102921
w
https://team.inrupt.net/common/popup.html:24:102921
```

Is that the same thing you're seeing?

**Comment by oshihirii** [comment]
Update for reference:  

The original issue was on an iPad.

I just tried the same steps in the original post in the environment detailed below and I was able to login:

Windows 10 Pro
Chrome Version 70.0.3538.67 (Official Build) (64-bit)

The interface is quite difficult to navigate though.  

The link below has a nice CSS framework if anyone wanted to look into that (minimal nice styling by default) - I am not clear what each section/button/ link represents and does in the inrupt interface, so don't think I'd be able to help very much.  

https://getuikit.com

**Comment by RubenVerborgh** [comment]
> The original issue was on an iPad.

Yes, we had to work around a Safari bug: https://github.com/solid/node-solid-server/pull/872

> The interface is quite difficult to navigate though.

Point taken 😄 This is a developer version, but Inrupt is working hard on a smooth UX. Stay tuned!

**Comment by oshihirii** [comment]
Sorry if this is not the place for such a “random” question, but how can I quickly understand the underlying concepts of this technology (I am guessing it is the ‘semantic web’?).  At very first glance, it looks like a way to codify information types (nouns?) and the way they interact with each other (verbs?), but when I look at a page like this: 
https://data.verborgh.org/ruben , it seems promising but when I click on the links they lead to more links and i’m not really sure what is happening.  Again, just sharing this experience in case it is helpful understanding a ‘new user’ experience.  Thank you.

**Comment by oshihirii** [comment]
Sorry if this is not the place for such a “random” question, but how can I quickly understand the underlying concepts of this technology (I am guessing it is the ‘semantic web’?).  At very first glance, it looks like a way to codify information types (nouns?) and the way they interact with each other (verbs?), but when I look at a page like this: 
https://data.verborgh.org/ruben , it seems promising but when I click on the links they lead to more links and i’m not really sure what is happening.  Again, just sharing this experience in case it is helpful understanding a ‘new user’ experience.  Thank you.

**Comment by RubenVerborgh** [comment]
> Sorry if this is not the place for such a “random” question

Better to start a new issue per topic, that makes it more easily findable.

> how can I quickly understand the underlying concepts of this technology (I am guessing it is the ‘semantic web’?).

Try:
- https://solid.inrupt.com/docs/intro-to-linked-data
- http://rubenverborgh.github.io/WebFundamentals/semantic-web/

> [data.verborgh.org/ruben](https://data.verborgh.org/ruben)

Okay, but this is advanced stuff already :-) It's a query interface.
If you want to understand, you can check:
- https://rubenverborgh.github.io/WebFundamentals/linked-data-publishing/#linked-data-fragments
but you don't need that for Solid.
