### ISSUE TITLE
login problem

### ISSUE THREAD

**Issue by Bart-Heymans** [solid/solid#173]
I made a Pod with username Bart Heymans, when I try to log in I get the message "site unreachable"

**Comment by RubenVerborgh** [comment]
Thanks for letting us know. We need to disallow spaces in usernames: https://github.com/solid/node-solid-server/issues/674 

You can try creating another pod without a space in your username.

**Comment by Bart-Heymans** [comment]
That is what I suspected.
Thanks.
Please remove the old pod.
On Github spaces where already not allowed
