### ISSUE TITLE
Usernames with '.' lead to TLS certificate errors

### ISSUE THREAD

**Issue by bbustin** [solid/solid#179]
If one creates a username that contains a `.` such as `firstname.lastname`, there is a TLS certificate error. This occurs because the domain is constructed from the username. The wildcard in a wildcard certificate only applies to the subdomain and not a subdomain of a subdomain.

In our example if username `firstname.lastname` were to sign up for a pod at solid.community, the domain would be `firstname.lastname.solid.community`. The SSL certificate for solid.community is only valid for `*.solid.community`, not `*.*.solid.community`.

While this is not a problem with Solid per-say, it seems there need to be either changes to how the pods are deployed or limitations to keep the usernames from containing a `.`.

**Comment by kjetilk** [comment]
Yeah, it has been fixed in https://github.com/solid/node-solid-server/issues/818 but not yet released.

**Comment by bbustin** [comment]
Thanks. Glad the issue was known and taken care of.
