### ISSUE TITLE
Implement a Welcome app (redirect to it after signup)

### ISSUE THREAD

**Issue by dmitrizagidulin** [solid/solid#18]
To improve the user signup experience, implement a Welcome / intro app which the user gets redirected to after completing signup. 

The app should have the following initial functionality:
1. Display what the user's newly-created WebID is
2. Link to Profile Editor app (and preferably to a list of other apps to try)

See also: 
- [solid-signup/5 - Redirect user to their new account once signup is done](https://github.com/solid/solid-signup/issues/5) 
- [gold/69 - After the cert has been issued, what then?](https://github.com/linkeddata/gold/issues/69)

**Comment by dmitrizagidulin** [comment]
Created https://github.com/solid/solid-welcome-app to address this

**Comment by ebporter** [comment]
We were calling that "Dashboard Lite" -- a landing page for after you go through the Sign Up experience. I've attached my original Balsamiq view.
![dashboard lite](https://cloud.githubusercontent.com/assets/7805740/16011827/f1c029ca-3154-11e6-8640-9f346b9a1f1a.png)
But I think it would be better to link to the new Connections app out of the gate, so I've made a new version:
![dashboard lite 2](https://cloud.githubusercontent.com/assets/7805740/16011961/6e7c160e-3155-11e6-9a01-de7ac0447d46.png)

**Comment by ebporter** [comment]
I think this is the task of redirecting to a landing page and making sure the callback contains the person's WebID, and [Lightweight dashboard.](https://github.com/solid/solid-dashboard-ui/issues/1) is the UI for the actual page.

**Comment by RubenVerborgh** [comment]
Technical enabler for that at https://github.com/solid/node-solid-server/issues/1057

**Comment by dmitrizagidulin** [comment]
I think this can be closed; various server implementations have now implemented some sort of after-signup user experience.
