### ISSUE TITLE
 problem with protocol

### ISSUE THREAD

**Issue by easylistbrasil** [solid/solid#182]
I know it is experimental, but when it registers through the https://solid.github.io/solid-signup/ link or accesses the nick.databox.me link it is redirected to an http protocol and not https, if the proposal is privacy and security, it is difficult for someone to want to bet on the project soon.

**Comment by kjetilk** [comment]
Hmmm, databox.me is a different implementation, and not an Inrupt project. Actually, I'm not sure where that page comes from, but somebody else in the company may now. https://solid.community/ and https://inrupt.net/ are the servers we operate. 

Hopefully, the Go implementation behind databox.me will get going again too, but for now, please use one of the above! :-)
