### ISSUE TITLE
Question: Regional Constraints

### ISSUE THREAD

**Issue by gibsonf1** [solid/solid#199]
Assuming a person or organization wanted to constrain access to their POD regionally, for example within a certain country, is there an approach both in the ontology and technically to allow this?

**Comment by kjetilk** [comment]
I have been thinking a bit about this, as it is clearly an interesting question, I have not found a concrete solution (like you cannot simply have a list of WebIDs, that list would be too large for for example a nation), but note that there is an `acl:agentClass` property, and my feeling is that something could be done to reason about class membership for this kind of use case. But it is definitely in the "future work" category.

**Comment by Mitzi-Laszlo** [comment]
You can find more conversation on this subject here https://forum.solidproject.org/t/question-regional-constraints/394

**Comment by JornWildt** [comment]
I think the basic question is - how do an agent prove that it belongs to a certain region? Not all countries have national digital identities and none of them are interchangeable.

So while you could state a `acl:agentClass` or similar, you would be hard pressed to find a way to let the agent prove its nationality. GEO-IP lookup could work to some extend, but can be spoofed in different ways.

**Comment by kjetilk** [comment]
Yes, indeed. In some places, it would be pretty simple, like the Nordics :-) but in other places, it is very, very hard. You could potentially base it on a Web of Trust, where a strong set of people certify each other's regional status, but it may be sensitive, different groups have different standards, and so on. 

Anyway, lets take the discussion to the forums, it is better suited there!
