### ISSUE TITLE
Tutorials link at bit.ly down

### ISSUE THREAD

**Issue by Samsemilio** [solid/solid#2]

**Comment by melvincarvalho** [comment]
Where is it supposed to lead?

My tutorials page is at : 

https://melvincarvalho.gitbooks.io/solid-tutorials/

But not sure it's the same one ...

**Comment by Samsemilio** [comment]
Its this link in your readme:
![bildschirmfoto 2015-12-11 um 19 30 59](https://cloud.githubusercontent.com/assets/747161/11752091/d67f8a78-a03d-11e5-9e88-924c9cf1f086.png)

**Comment by nicola** [comment]
Thanks! just updated!
