### ISSUE TITLE
some advices

### ISSUE THREAD

**Issue by spitWind** [solid/solid#204]
1. Develop standard data formats
Such as bookmarks
```
{
href: "xxx.api.com",
title: "bookmarks1"
}
```
2.
Data view separation
Such as vue, you can load different data
At the same time, network isolation prevents data from being uploaded to the server.
Users can manage their own data with different data control programs

**Comment by melvincarvalho** [comment]
@spitWind very good advice!

I hope you'll be happy to learn that solid has spent almost 20 years standarizing data formats.  This is what has become known as Linked data.  Indeed, the aim is to separate data, view and controller logic, in a declarative way.

Some more notes.

https://solid.inrupt.com/docs/intro-to-linked-data

**Comment by csarven** [comment]
@spitWind  Web Annotation's https://www.w3.org/TR/annotation-vocab/#bookmarking motivation is one of many that fits under the WA Model: https://www.w3.org/TR/annotation-model/ . Is that adequate for what you had in mind? If not, can you elaborate on why?
