### ISSUE TITLE
Undefined status: 200 

### ISSUE THREAD

**Issue by piecurus** [solid/solid#206]
on ubuntu/chromium, constantly getting the message below 

Outline.expand: Unable to fetch <https://pcasale.solid.community/profile/card>: Failed to load  <https://pcasale.solid.community/profile/card> Fetcher: Error trying to parse <https://pcasale.solid.community/profile/card> as Notation3:
Line 1 of <https://pcasale.solid.community/profile/card>: Bad syntax: expected directive or statement
at: "mycard
":
undefined status: 200

**Comment by kjetilk** [comment]
Oh, this seems to be closely related to #206, we'll follow up there.

**Comment by RubenVerborgh** [comment]
I think @kjetilk meant #165, so let's follow up there.

The problem is the following:
```
$ curl 'https://pcasale.solid.community/profile/card'
mycard
```

This is invalid RDF, hence the error. @piecurus if you have any idea what operation put `mycard` in the file, please let us know.
