### ISSUE TITLE
"The resource you are trying to access xxxxx requires you to log in."

### ISSUE THREAD

**Issue by TheodoraPetkova** [solid/solid#207]
Hey there!

I have an issue with a resource not showing - actually showing only when I am logged in with my solid account, and if I am viewing it not logged I don't have permissions to see it.
When I right click on the broken image,  and open the image address I get this (when not login it)

The resource you are trying to access (https://teodora.solid.community/profile/teodorapetkova.png) requires you to log in.

Maybe I have added my pic the wrong way. (I dragged and dropped it into my browser :))
@LucJallois - who also tried to open that resource when logged in with his solid account, suggested it has something to do with ACL, but I have no clue how to fix this.

Thanks!

**Comment by RubenVerborgh** [comment]
@TheodoraPetkova You would need to go to the folder https://teodora.solid.community/profile/, log in there, and then you can adjust sharing settings with the rainbow icon. You would need to make the folder publicly readable.

**Comment by TheodoraPetkova** [comment]
@RubenVerborgh thank you so much. I wasn't aware of the so many think I can tweak into this. I ended up here:
![screen shot 2018-10-15 at 11 16 22 am](https://user-images.githubusercontent.com/40993908/46938245-ea8d3180-d06b-11e8-918b-eb00b4fad508.png)
Adn stopped the specific sharings. 
Where do I see these sharing seting and can  refine them?
Thank you on emore time for your time and attention!

**Comment by RubenVerborgh** [comment]
You're welcome! You would need to drag the globe onto "Viewers", which would give the public read access.

**Comment by RubenVerborgh** [comment]
I confirm I can see your profile picture now!

Not sure I understand your next question, let me know if I can help. I'll close this issue for now (so it remains a nice atomic FAQ); feel free to start another.

**Comment by TheodoraPetkova** [comment]
OK! Atomic on. It is just I feel like I am bringing "noise" to the technical things with my UX questions. But the feel free part make me brave and I will go on and ask the question in another thread.

**Comment by RubenVerborgh** [comment]
Don't hold back—all of this is important feedback!

**Comment by melvincarvalho** [comment]
> It is just I feel like I am bringing "noise" to the technical things with my UX questions

Definitely not noise.  These UX insights are invaluable, if we want to bring solid to a wider audience.

**Comment by TheodoraPetkova** [comment]
Thank you. I want that too! I will try then to create questions in a more FAQ manner.

**Comment by RubenVerborgh** [comment]
@TheodoraPetkova You might also like our new forum at https://forum.solidproject.org/, in which we are trying to create such a FAQ. Post your questions wherever you feel most comfortable.

**Comment by TheodoraPetkova** [comment]
p.s. Generaly I have scheduled 30-60 mins per day to do one thing in Solid. So I will be around :) Than _you_ for being around too.

**Comment by TheodoraPetkova** [comment]
@RubenVerborgh what a great discobit you have there! Awesome. A cool experience and intro for people not used to such environments. I feel more comfortable to stay here for now, but with time I will move to spend more time with disco :)

**Comment by justinwb** [comment]
@TheodoraPetkova Thanks for participating! This level of engagement is really valuable to us and the community as a whole!
