### ISSUE TITLE
Can't read access control file

### ISSUE THREAD

**Issue by MadsHolten** [solid/solid#208]
While playing around with the drag-drop system I managed to reduce my own rights in the sharing tab meaning that I now don't have access to anything.

1) How do I recover my access?
2) I think you should add a warning or something so that this doesn't happen to other people

```
Error reading default ACL. status 403: (Sharing not available to you)Can't read Access Control File <https://mads.inrupt.net/profile/card.acl>: Failed to load <https://mads.inrupt.net/profile/card.acl> Fetcher: <https://mads.inrupt.net/profile/card.acl> Forbidden status: 403
```

**Comment by megoth** [comment]
@MadsHolten we are working on ways to allow users resolving this on their own, but for now can you send an email to support@inrupt.com? I'll close this issue for now, and hope we're able to resolve this for you via email ^_^
