### ISSUE TITLE
an invitation to Tim Berners-Lee from China

### ISSUE THREAD

**Issue by spyhole** [solid/solid#212]
Hi，my name is Daniel WANG, you can get more details about me from https://bitcoinfoundation.org/forum/index.php?/profile/3463-danielwang/ 

Would you like to discuss blockchain and related issues with Chinese professionals in this field via WeChat, the most polular social media in China? Maybe I could help you. Well, you could download WeChat from https://weixin.qq.com/ ,BTW, my WeChat ID is spyhole .

Looking forward to your reply.

**Comment by RubenVerborgh** [comment]
Dear @spyhole, you can get in touch with @timbl through https://www.w3.org/People/Berners-Lee/ or chat with us at https://gitter.im/solid/chat.
