### ISSUE TITLE
How do I update my avatar and invite you to my Gitter?

### ISSUE THREAD

**Issue by spyhole** [solid/solid#218]
its name Dualvectorfoil https://gitter.im/Dualvectorfoil/

**Comment by spyhole** [comment]
?

**Comment by justinwb** [comment]
Hi Daniel. For questions specific to Gitter, please get in touch with Gitter support. You can chat with them directly at [Gitter Support](https://gitter.im/gitterHQ/gitter)

Since this isn't a question specific to Solid I'm closing this ticket. Thanks!
