### ISSUE TITLE
Can't delete profile

### ISSUE THREAD

**Issue by Gralen84** [solid/solid#219]
I've read through the documentation around the API for deleting an account, however I seem to have messed this up, as all I've been able to accomplish is deleting my profile card.  I'm looking to remove my pod from the Solid.Community server and create a new POD on a new node server I'm looking to set up.  When looking via the forums I can find nothing simple to follow for deleting an account either.  I did like one persons suggestion back in 2016 that there's either a UI management button, or a "Delete Account" on the /settings page.

Either way, please delete my account as I don't want to have accounts all over the place, and please provide directions on how to delete accounts, as I'm sure others will be looking into this for various reasons.

**Comment by kjetilk** [comment]
OK, we'll look into this. Just one question: When did you create the account? The user interface that we have towards deleting accounts applies to new accounts, so we still have to delete accounts manually that are older than the last release. :-)

**Comment by megoth** [comment]
If you don't have the link to delete your account, you can visit https://[YourUsername].solid.community/account/delete.
