### ISSUE TITLE
JS error, Profile: NamedNode IRI must be absolute

### ISSUE THREAD

**Issue by awegmueller** [solid/solid#224]
My public homepage is https://andrewegmueller.solid.community/. When I log in with my Web ID "andre.wegmueller" and click on "Profile", the URL changes to ./profile/card and a white, empty page appears. In the JS-error log the following error shows up:

named-node.js:57 
Uncaught (in promise) Error: NamedNode IRI "andre.wegmueller" must be absolute.
     at new t (named-node.js:57)
     at Object.p (data-factory.js:58)
     at l (signin.js:88)
     at g (signin.js:780)

**Comment by RubenVerborgh** [comment]
> When I log in with my Web ID "andre.wegmueller"

That's the problem: a WebID must be an absolute URI: https://github.com/solid/solid-ui/issues/53
The field should be left empty when you do not have an existing WebID. We should make this much clearer in the UI.

The best advice is probably to delete your POD and to sign up again.

**Comment by awegmueller** [comment]
@RubenVerborgh  Thanks for your quick reply. Is there a function somewhere to "delete my POD"? Could you provide a link for that? Or should I simply abandon my current account and create a new one?

**Comment by megoth** [comment]
@awegmueller https://forum.solidproject.org/t/how-can-i-delete-my-account-on-a-solid-pod-provider/25 is a thread that explains how to delete an account (but in short, I think you can visit https://solid.community/account/delete and start the process there).

**Comment by awegmueller** [comment]
@megoth Thanks for the link. I've deleted and re-created my account without a Web ID. That seems to work. I guess it is a good idea to make the Web ID field less important on the Register form, and/or perform a check, if the Web ID URL is available via http.
