### ISSUE TITLE
Move blockchain consesus mechanism to solid

### ISSUE THREAD

**Issue by ghost** [solid/solid#232]
IBM Hyperledger Fabric Consensus manager show a very good modelized example!
Plug-and-Play

**Comment by MasterJames** [comment]
Okay I calmed down, but burning processing is a bad way to form a consensus, in a processing based economy of the future, and logically can't survive over alternative solutions, but maybe blockchain will get there sooner and be hard to replace. I just don't think it's technically the right way. It has it's own problems, and not yet as established, as the existing systems that evolved to what the global computer network is today.
Looking back I wasn't entirely sure what you where saying and asking and looked into it more. Maybe that was the point. Maybe you're asking what can be adapted from what's happening there.

https://medium.com/swlh/how-to-talk-to-a-company-about-blockchain-the-ibm-hyperledger-example-2-2-fb680e9ee346 

There's merit to understanding more about what is happening currently in those regards. 

Maybe be clearer on what your thoughts or proposals are?
