### ISSUE TITLE
Broken data pod

### ISSUE THREAD

**Issue by stefaanh** [solid/solid#236]
Allthough I am succesfully logged in using my inrupt id I get a raw "card" page after clicking Profile Data. expanding gives me this:
`Outline.expand: Unable to fetch <https://<my-user-name>.inrupt.net/profile/card>: Failed to load  <https://<my-user-name>.inrupt.net/profile/card> Fetcher: <https://<my-user-name>.inrupt.net/profile/card> Unauthorized status: 401`

It is possible that I broke some things by deleting essential data.
Still I experimented while leaving private data in the open... awkward, but then again, my fault.

Everything I try gives me more or less the same message. Even when I actually can reach some of my data:
`Outline.expand: Unable to fetch <mailto:<my-user-name>@domain.tld>: Failed to load  <mailto:<my-user-name>@domain.tld> Fetcher: fetcher: Unsupported protocol`

The home button gives me

`You don't have, or you couldn't acess,  type indexes --lists of things of different types. Create new empty ones? Error: [LTI] Error: Can't find a preferences file pointer in profile <https://<my-user-name>.inrupt.net/profile/card>`

Could someone delete my account, so I can start all over?

**Comment by megoth** [comment]
If you registered your email when registering your account, you can follow the steps at https://forum.solidproject.org/t/how-can-i-delete-my-account-on-a-solid-pod-provider/25/2

**Comment by stefaanh** [comment]
@megoth Thank you very much. That did the trick. I must ad that the first account-delete-link sent by inrupt .net had a very short validity time. With the second one I was on time.
