### ISSUE TITLE
Send out welcome emails to newly created accounts (recommendation for servers)

### ISSUE THREAD

**Issue by dmitrizagidulin** [solid/solid#24]
If the user specifies the optional email address (used for account recovery, etc) on a signup app (such as [solid-signup](https://github.com/solid/solid-signup)), send them a Welcome to `<provider name>`! / "welcome to Solid" sort of email.

Include:
1. Their WebID (that they can use for logins, etc)
2. Links to documentation / resources
3. Link to their Profile (via a profile editor)
4. The Account Recovery link

Considerations:
- This should definitely be a plugin-type mechanism (at very least, a config option for the solid server)
- Sending emails is operationally difficult (since they're prone to end up in spam filters, etc). Consider offering something like [Sendgrid](https://sendgrid.com/) as an option for server operators.
- Some server operators might want to make the recovery emails required at signup, and have an "email verified" flag on the account.

Implementations:
- [ ] LDNode: https://github.com/linkeddata/ldnode/issues/195

**Comment by ebporter** [comment]
I like the welcome message that Instagram sends -- very friendly, very inviting:
[Welcome to Instagram, ebport.pdf](https://github.com/solid/solid/files/312324/Welcome.to.Instagram.ebport.pdf)

So, with that in mind, here is recommended text/layout for the HTML email:

<image>
Welcome to <provider>, powered by Solid.
Welcome to the revolution! At Solid, we're transforming the Web by letting people control their own data, not let their data control them. With Solid:
* Own Your Data -- You decide where to keep your data and who gets to use it.
<image>
* Use Any App You Like -- Solid data is separate from the apps that use it, allowing you to switch easily between apps, taking your data with you.
<image>
* Let Data Be Free -- Free in the sense of freedom! Free yourself from repeated data entry; reuse your data across Solid apps.
<image>
* Invent Something New -- Explore, imagine, create. By having data from all your Web activities in one place, unleash the power of you.
<image>

Nitty-gritty stuff you don't want to forget:
* Your WebID for signing in to Solid apps: <WebID>
* Your Solid Profile, which is your public face on the Web: <Solid Profile>
* Account recovery, in case you need to reclaim your credentials: <link to Account recovery>

We're so excited to have you in the Solid family!

The Solid Team

**Comment by dmitrizagidulin** [comment]
This can be closed (has been implemented in node-solid-server and other implementations)

**Comment by spygency1** [comment]
NEED URGENT HELP?!!

NOTE:MESSAGE ONLY THIS ACCOUNT
#🇬🇧Expert Here To Assist In Any Cyber Issues General_Hacking_Recovery_Spy_Blackmail_Stolen,Lost BTC_Hacked Phones ☎️ 📥
🌎Facebook hacking - recovery
🌎Instagram hacking - recovery
🌎Snapchat hacking - recovery
🌎Lost money(investment scams) recovery
🌎Cheating partner spy (online)
🌎Crypto wallet hacking
🌎Phone hacks📱
🌎Message hacks & tweaks

For swift response send a message to my social media accounts, we are active 24/7 to solve all your Online ETHICAL HACKING issues 

INSTAGRAM 📥 spygency.1
EMAIL 📧 spygency@gmail.com
