### ISSUE TITLE
Solid and Fediverse

### ISSUE THREAD

**Issue by cerisara** [solid/solid#242]
Hi,

The Fediverse is gaining popularity as a decentralized and interoperable social media. How does it differ from Solid's vision ? Do you think about ways to make Solid and the Fediverse interoperable ? How to get the best of both worlds ?

**Comment by csarven** [comment]
Which "fediverse"? ;)

Personal opinion: I think the general visions are aligned. There are some technical differences, but possible to interop. For instance, at the moment, Solid doesn't define server-server interactions, only client-server ( related: https://github.com/solid/specification/issues/36 ) . ActivityPub defines server-server that can be taken up. AP's client-server with the JSON-LD flavour, much narrower than Solid's can be taken up.. and that should interop as well among a class of applications. There is room for Solid to also specify server-server interactions. 
See also: https://gitter.im/solid/chat?at=5b7d401994f8164c1782f742 , https://gitter.im/solid/chat?at=5b7d450094f8164c178316ae , https://github.com/solid/node-solid-server/issues/621 ..

**Comment by cerisara** [comment]
Thanks, it all makes sense. I love the fediverse for many aspects, and I love the concepts behind dokieli; that's why I'd love even more seeing both getting interop, because that'd result to more than just the sum of both: I believe interop is the key to success, the most important added-value of decentralization/federation that may bring users into them; I'll for sure think about it more in the near future: there may really be something big to do there ;-)

**Comment by csarven** [comment]
More opinion: Putting the principles/values aside, the initiatives are sufficiently similar, and what brought many folks together was to create an interoperable space, regardless of their technical preferences. Historically (2007, give or take a few years), federated web initiatives was a reaction - but not entirely - to centralised web20ish social networking services. The use cases were derived from what people were used to doing on the social Web. To a good extent, Solid shares those as well, but it could be said that the underlying approach is broader (ie. applicable to domains outside of "social web") and can potentially materialise a richer and diverse ecosystem, business models and so on. TBD.

See also:
* https://www.w3.org/DesignIssues/CloudStorage
* https://www.w3.org/2005/Incubator/federatedsocialweb/
* https://www.w3.org/2008/09/msnws/report.html
* https://www.w3.org/TR/social-web-protocols/

If you think this information sufficiently addresses your question, would you like to close this issue? You may also want to raise this in https://gitter.im/solid/chat to get more feedback.

**Comment by cerisara** [comment]
Sure, thanks again for all these pieces of information !
