### ISSUE TITLE
Timeline: When usable by average (non geek) user?

### ISSUE THREAD

**Issue by guettli** [solid/solid#246]
What is your timeline? 

When will solid usable by an average human being (a non geek which is not able to write computer programs)

**Comment by elf-pavlik** [comment]
This question might fit better on https://forum.solidproject.org/

**Comment by guettli** [comment]
Do you think the forum is a better place for this question. For me a forum is mostly used  by software users. 

This question can't be answered by software users. It needs to be answered by someone who creates this software. 

That's why I think the issue tracker fits very well.

But my question was indirectly answered.

It was answered indirectly because no answer was given.

Now I think: This project is just hot air - it won't be usable in the next months.
