### ISSUE TITLE
Write a client-side alternative for globbing

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/solid#253]
https://github.com/solid/solid-spec/issues/145 discusses the removal of globbing. That is only possible if we have a client-side replacement.

Here's a suggestion on how this can work:
- the glob pattern is parsed on the client
- the client makes requests to the containers to obtain matching files and folders
- the client concatenates them

Note that the concatenation can happen in a streaming way.

What I don't think we need:
- an extension to the spec
- anything HTTP/2-specific (HTTP/2 will automatically optimize the requests being sent)

**Comment by RubenVerborgh** [comment]
Tentatively assigned @michielbdejong; up for discussion.

**Comment by cybertop35** [comment]
:(

**Comment by RubenVerborgh** [comment]
@melvincarvalho Could you share some examples of apps that use globbing? Then we can see how they use it, which can inform what the client-side API should look like.

**Comment by RubenVerborgh** [comment]
Literally all we have to do is this: https://github.com/solid/node-solid-server/blob/v5.0.0/lib/handlers/get.js#L133, with the only caveat that the `glob` function of https://github.com/solid/node-solid-server/blob/v5.0.0/lib/handlers/get.js#L146 needs an HTTP/LDP-level equivalent. If we crack that, then we're good. An initial implementation could be very naive (just breadth/depth-first search of all descendants of a folder, and filter those matching the glob), and optimizations could be added later (don't search folders that can never match the glob).

**Comment by gobengo** [comment]
The elephant in the room on this seems to be the over-the-wire cost of transmitting a complete directory listing to the client for directories with lots of keys.

Likely server-side globs where the filtering is done physically close to the data (even by the same data store) can be done in less than a second round-trip best/average case. If the result size is big, there are bandwidth time/space costs, but that's not unique to server-side globbing. In fact, it's the best case for client-side globbing.

e.g. directory of my photos has 10000 keys (a conservative estimate for most people in the cameraphone era). Each filename is, let's say, a string as big as a UUID (36 characters). At 2 bytes per character, that's 10000 keys * 36 chars * 2 bytes = 72000 bytes = ~ 72MB just of filenames over the wire. (576 megabits). Average 4G data speed of 15Mbit/s (let alone 2G/3G , common around the world), that's 576/14 = 41s to perform the glob (best case). This all is O(n) >= n. i.e. it only gets more time consuming as I use solid for more things. I don't think anyone can honestly argue that this is acceptable for widespread adoption for everyday personal cloud computing use cases.

I am supportive of prototyping this (why not?), and it is definitely *possible to build*, but we must be honest about the expected time/space complexities of the different alternatives and what are the acceptable bounds?

e.g. linux doesn't do fs globbing in the kernel (I think?), but instead it's usually a feature of shell programs in userspace. But that's not the same as doing the globbing over the wire. We still ssh into a machine physically close to the fs/kernel (usually same machine), run the shell close by, and send the *results of the glob* to the shell client.

With all that said, I still am sympathetic to not requiring this-challenging-to-scale feature in the most minimal version of the core spec. It could always be added again later when there are more resources to make reference implementations with different time/space complexities (e.g. implementing globbing by querying a real datastore with an index/view). It's common for web-scale systems to use an ensemble of multiple underlying datastores with different tradeoffs.

**Comment by RubenVerborgh** [comment]
> 72MB

* 0.72MB (without gzip; related filenames naturally lend themselves to that)

**Comment by gobengo** [comment]
@RubenVerborgh ha I was literally just editing to account for that. But that doesn't negate what really matters here: The algorithmic complexity of different alternative solutions.

**Comment by RubenVerborgh** [comment]
From extensive experience (http://linkeddatafragments.org/publications/jws2016.pdf): it's not as bad as you think.

And the scalable solution here will be querying. Globbing is just a poor man's query; let's replace that with a client-side solution, and built proper query interfaces instead.

**Comment by gobengo** [comment]
So let's just be honest about what are the pros/cons. From #145 the OP starts with 

> 1. No one really wants globbing. People want cross-file data access, and there are better ways of achieving that. Globbing has always been a hack for accessing data in multiple files. It was not thought through well (see below).

I don't pretend to know about this.

> 2. Globbing is expensive on the server-side.

Only if you implement it naively. Alternate datastores (or if the datastore is a filesystem, shell out to bash or a C lib instead of globbing in node). This assertion needs more justification.

> 3. Globbing can lead to denial of service (on server and client).

See 2. DDOS are a risk no matter what, e.g. by repeatedly getting full directory listings that are huge and taking up all available OS connections. It's not that unique to globbing. Practically, pros would deploy behind a DDOS-protecting middleware that makes this a non-issue.

> 4. Whatever can be achieved through globbing, can be achieved as efficiently without. With HTTP/2, there is zero overhead in just going through the files on the client side.

My argument above is meant to respectfully disagree.

> 5. Let's remove it soon before it is actually widely used and implemented.

No argument here.

---

So 1 and 5 are likely good reasons. But let's be real about it.

---

> And the scalable solution here will be querying. Globbing is just a poor man's query; let's replace that with a client-side solution, and built proper query interfaces instead.

Totally agree! +1

**Comment by akuckartz** [comment]
> 72000 bytes = ~ 72MB

?!

Seems to be more like 0.072 MB

**Comment by gobengo** [comment]
@akuckartz great point, I will edit to recalculate. Thank you for reviewing the math. It will definitely matter.

**Comment by RubenVerborgh** [comment]
People, [it's 0.72MB](https://www.google.com/search?q=10000++*+36++*+2+bytes+in+MB).

**Comment by RubenVerborgh** [comment]
@gobengo Please move pros and cons to https://github.com/solid/solid-spec/issues/145.

**Comment by gobengo** [comment]
moved that to https://github.com/solid/solid-spec/issues/145#issuecomment-475725287

@RubenVerborgh first napkin calculation corrected (and conclusion changed).

Now it is less than "an elephant in the room", at least if we accept the napkin variables I went with, which I think are fairly decent.

And hopefully we're better off for having done some estimation.

(thanks again @RubenVerborgh and and @akuckartz for fixing my silly mistake. Ruben, I didn't realize your first comment was pointing it out, just mentioning gzip. Apologies)

**Comment by melvincarvalho** [comment]
@gobengo globbing is not the same as using http, they are completely different URIs.  It would require reprogramming. and a LOT of testing.  A certainly dont have bandwidth for that right now, hence my formal objection.  Creating an http2 client would be cool, but is there a need for it?  Seems like ultra bike shedding right now.  I would much prefer to get node solid server working and bug free.

**Comment by melvincarvalho** [comment]
> @melvincarvalho Could you share some examples of apps that use globbing? Then we can see how they use it, which can inform what the client-side API should look like.

Playing ball here.  This is an example on the client side

https://github.com/solid-social/timeline/blob/master/app/app.js#L324

And another here

https://github.com/melvincarvalho/webid.im/blob/master/app/app.js#L442

Of course there is also also server side code for globbing too.

Im unconvinced by the portrayal of globbing as an optimization.  I mean, you could view the whole of linked data as a giant quad store, and then all we are doing is optimizations.  So how you do things count.  They are different URIs, so you are definitely comparing apples and oranges.

However, if you are able to prove that there's a like for like working replacement to the code above, I'll be both grateful and closer to convinced.  I dont think that will be easy tho, because, I had a perfectly working server for this app 4 years ago, and I've yet to see one since.  I have 1000s of lines of code ready to work, but have been waiting several years for the bugs to be cleared.  Let's do that first!

**Comment by RubenVerborgh** [comment]
Thanks for sharing.

> I dont think that will be easy tho, because, I had a perfectly working server for this app 4 years ago, and I've yet to see one since.

Mmm, that's bad news, if that means there is no working app with globbing, because then we cannot test replacement libraries with existing apps.

As I have explained in other threads, node-solid-server has become unmaintainable. We think that it is faster and more sustainable to write a new server than it is to fix NSS. So the possibility of leaving out globbing is something that can inform new servers. (This is also how the question came up; was talking to a developer last week who wanted to build their own server, and they asked whether globbing was mandatory.)

**Comment by melvincarvalho** [comment]
> Mmm, that's bad news, if that means there is no working app with globbing, because then we cannot test replacement libraries with existing apps.

No, it's just that node solid server is buggy.  It can be fixed.  It's close.  @michielbdejong is doing some testing on Wednesday.

> As I have explained in other threads, node-solid-server has become unmaintainable. 

Couldnt possibly disagree more.  It has been in a much worse state, and has been improving steadily over time.  

> We think that it is faster and more sustainable to write a new server than it is to fix NSS. 

Disagree completely.  But even if you go that route, there is a commitment to working on fixing and improving NSS 5.x.  My view is that your favoured option of a rewrite, well be shown to be a non optimal use of time and money.  Time will tell!


> So the possibility of leaving out globbing is something that can inform new servers. 

No, there isnt.  I have made a formal objection.  Tim might be able to override it, but i have several months of code using it, and we want to avoid throwing developers under the bus.

> (This is also how the question came up; was talking to a developer last week who wanted to build their own server, and they asked whether globbing was mandatory.)

Yes, it is.  More details on that server would be welcome.

**Comment by RubenVerborgh** [comment]
> > As I have explained in other threads, node-solid-server has become unmaintainable.
> 
> Couldnt possibly disagree more. It has been in a much worse state,

What I wrote is the opinion of all people who worked intensively on NSS since 4.x; especially the key people involved in 5.x. You're of course free to disagree, but it will be hard to find a more informed opinion than ours.

> > So the possibility of leaving out globbing is something that can inform new servers.
> 
> No, there isnt. I have made a formal objection.

I wrote "possibility". That is the very reason I started the spec issue. Your formal objection is helpful and has been noted, and we are working on a resolution in this very issue here.

Note that I am not on a religious (or any other) crusade against globbing. I am rather looking at what is a good contract between apps and the server, and I have concerns about globbing not being a good contract (hence the issue).

>  Tim might be able to override it, but i have several months of code using it, and we want to avoid throwing developers under the bus.

Reminder that a functionally identical client-side replacement is a pre-condition of even considering the removal of globbing.

**Comment by RubenVerborgh** [comment]
@melvincarvalho 

> This is an example on the client side
> 
> [solid-social/timeline:app/app.js@`master`#L324](https://github.com/solid-social/timeline/blob/master/app/app.js#L324)
> 
> And another here
> 
> [melvincarvalho/webid.im:app/app.js@`master`#L442](https://github.com/melvincarvalho/webid.im/blob/master/app/app.js#L442)

Thanks for these, hopefully good testing material once server bugs are ironed out. Two quick questions for you still.

1. Do you happen to have any more complex globs in the wild (anything beyond a single `*`)?

2. What was the last version of NSS where these apps worked? (Was it 3.x?) We could just test the globbing replacement against that version then, I just realized.

**Comment by melvincarvalho** [comment]
@RubenVerborgh 	yep ive had gold working, and NSS 3 and 4 I think, tho the main issues were not surrounding globbing which was quite fine.  More around the web socket library which sometimes times out.  Little things like this are important for things like chat.  But you dont really get to see these pain points until there's a stable server to work against.  And we didnt even have public servers before, except mine.  Things have moved a long way.

I only used simple globs /* (ie get content from a directory) which I think is all anyone used, and how globbing was intended.  I'm unsure anyone used it in another way, and it could indeed be over specifying it to do so.

**Comment by RubenVerborgh** [comment]
> I only used simple globs /* (ie get content from a directory) which I think is all anyone used, and how globbing was intended.

Ooh, thanks, this is huge. See https://github.com/solid/solid-spec/issues/147.
That makes a very big difference on both the server and building an alternative.
Please comment if you have any memories or pointers regarding the intention of globbing.

**Comment by melvincarvalho** [comment]
> Reminder that a functionally identical client-side replacement is a pre-condition of even considering the removal of globbing.

So yes I'm interested.  Looking at my code, it was largely an experiment and learning to use angular and javascript back then.  But you might be able to read through some of it.

Basically I had a queue of urls to be fetched, then when fetched they would trigger some business logic and a rerender using two way binding.  So if there's a neat way to use HTTP2 that's cool.  But I had a private discussion with you before along the lines of "everything breaks".  What that means is that whenever you introduce a new technology you will always find some edge case that blows up.  It takes ages to find them and longer to debug, and sometimes never resolve.  Something as simple as websockets breaks badly in chrome in distributed apps.  

So while I would welcome some HTTP2 libs (assuming there's a need), there will need to be a longish overlap and sunset period in any case, simply due to the nature of user agents and edge cases they throw up.

**Comment by RubenVerborgh** [comment]
> there will need to be a longish overlap and sunset period in any case,

Good point, need to document that in https://github.com/solid/solid-spec/issues/145.

**Comment by RubenVerborgh** [comment]
> Im unconvinced by the portrayal of globbing as an optimization.

BTW Just found that this is actually what the spec currently says:

> > to optimize certain applications we needed to aggregate
all RDF resources from a container

**Comment by melvincarvalho** [comment]
Very subtle.  But as I say everything we do in linked data is a type of optimization.  

You could think of apps as taking a slices of the giant global graph and displaying them, so then the app itself could be regarded as an optimization of a state machine.

I get your point, I dont think this one is worth dwelling on ...

**Comment by RubenVerborgh** [comment]
Not dwelling, but I'm editing that text for a PR for https://github.com/solid/solid-spec/issues/147, so might be an opportunity to change that wording with it if you think that is appropriate.

**Comment by RubenVerborgh** [comment]
Implemented in https://github.com/solid/ldp-glob; live demo at https://solid.github.io/ldp-glob/demo.html?https://drive.verborgh.org/public/
