### ISSUE TITLE
lock when save two gifs into dokieli

### ISSUE THREAD

**Issue by FutureLearnSole** [solid/solid#271]
![](https://github.com/FutureLearnSole/pulse-project/blob/master/brave_UK5pAa79Oy.png?raw=true)

_my first bug report_

**Comment by csarven** [comment]
@FutureLearnSole It would be great if you can provide more information on how to reproduce this issue.

@megoth  , @kevin-inrupt , I think this should probably move to https://github.com/solid/mashlib

**Comment by FutureLearnSole** [comment]
i could do the favor and close this and create it over there for you as well ^o^

_off topic,_ i'm thinking of putting up a gif thread of my interactions as Solid progresses (with the UI,etc) and other related stuff like this visual https://mdsolehinsabtu.solid.community/public/diststruct2.html

Really would like to be part of the movement in that way as well, is there a space you know of for such? probably [solid/talk](https://github.com/solid/talks) or [solid/intro-to-solid-slides](https://github.com/solid/intro-to-solid-slides)?

**Comment by megoth** [comment]
Would like to understand the issue a bit more before deciding where it should be moved. @FutureLearnSole Could you describe a bit more what you did before the bug happened?

**Comment by FutureLearnSole** [comment]
Edit > add one `.gif` by drag paste from local > save > save complete > add another `.gif` under it > save > no save complete > close tab

**Comment by megoth** [comment]
I suspect this has something to do with dokieli directly, in which case the issue should be moved to [the dokieli repo](https://github.com/linkeddata/dokieli), or with the "glue" between Data Browser and dokieli, in which case it should be moved to [the solid-panes repo](https://github.com/solid/solid-panes/), but I cannot know before doing more research.

@csarven do you have any more ideas about this? If not, I propose that we move it to solid-panes and let the team work on it as part of fixing bugs on the Data Browser. (@FutureLearnSole just to note, it might take some time before we're able to tackle this issue.)

**Comment by FutureLearnSole** [comment]
Thank you for taking a look into this and gifting your insights. doing what i can leaving crumb trails here and there.

**Comment by FutureLearnSole** [comment]
_exp_
