### ISSUE TITLE
Does solid use acl:accessToClass?

### ISSUE THREAD

**Issue by sandhawke** [solid/solid#36]
One can imagine how acl:accessToClass would be useful, but I haven't heard of anyone using it.   So do we mandate it be implemented in solid servers or leave it out?

suggestion: leave it out for now, at least

**Comment by bblfish** [comment]
I use it. I have an acl that gives a user r/w access to all acls, and all other users read access.

```Turtle
[] acl:accessToClass [ acl:regex "https://(\\w+\\.)?localhost:8443/.*[.]acl" ];
   acl:mode acl:Read;
   acl:agentClass foaf:Agent .
[] acl:accessToClass [ acl:regex "https://(\\w+\\.)?localhost:8443/.*" ];
   acl:mode acl:Write, acl:Read;
   acl:agent <card#me> .
```

This file is `wac:include`ed  from every other file created.

**Comment by bblfish** [comment]
patterns on URLs are not the only use case. One could perhaps also specify sets of resource by their mime type or primary topic, etc... Perhaps that would be a better way to specify acls without having to define regular expressions on urls.

**Comment by dmitrizagidulin** [comment]
Checked with @deiu and @timbl about this, the consensus is that Solid implementations will not support `accessToClass`.
(Marking as 'pending closing'.)

**Comment by bblfish** [comment]
Btw, regexes are not necessarily the only way to use accessForClass. One could also use owl something like this

```Turtle
[] acl:accessToClass [ a owl:Restriction; 
                                    owl:allValuesFrom <.>; 
                                    owl:onProperty ldp:contains ] 
                                 ];
   acl:mode acl:Read; 
   acl:agentClass foaf:Agent .
```
```

**Comment by dmitrizagidulin** [comment]
@bblfish - the recommended way of doing that (setting permissions for all the contents of a container) is via acl:defaultForNew (soon to be renamed to acl:default)
