### ISSUE TITLE
Standardize on the term "app" instead "skin" for viewers/editors/renderers 

### ISSUE THREAD

**Issue by dmitrizagidulin** [solid/solid#4]
(Moved from https://github.com/solid/solid-spec/issues/65.)

This first started as a [discussion on PR 174](https://github.com/linkeddata/ldnode/pull/174#discussion_r49127831), where I asked about the `--skin` command line parameter that's passed to [ldnode](https://github.com/linkeddata/ldnode) to specify the default app it's going to use to render a resource.

"Skin" is an overloaded term, that most developers and web users understand to mean in the UI sense, a "theme". What is currently referred to as a "skin" by Solid devs, is the bit of app code (a viewer/renderer/editor etc) that is presenting the resource that's being browsed. So, for example, [Warp](https://github.com/linkeddata/warp) is a "skin", since it determines how a particular resource (the file or directory being browsed) is displayed.

(@csarven suggested the term "default app", in that initial discussion.)

In the Fri Jan 8th team dev meeting, we discussed this issue again. There seems to be a general consensus that we should rename the term. 

The question is - to what.

The candidates mentioned so far are:

1. "default app"
2. "fallback app"
3. "suggested app" or "preferred app"
4. "viewer" or "editor"
5. "opener"
6. "component" (in the Ember.js / Angular sense, which means "a view with some controller code/logic to go with it)
7. "renderer"

What would be your preferred term?

(Discussion-to-date summary: @deiu and @nicola is ok with standardizing on "app" terminology).

**Comment by nicola** [comment]
@dmitrizagidulin  can we close this?

**Comment by dmitrizagidulin** [comment]
Shortly. I want to also rename the term in Gold, just in case.

**Comment by dmitrizagidulin** [comment]
Ok, also renamed in Gold. closing.
