### ISSUE TITLE
GSoC 2016

### ISSUE THREAD

**Issue by akuckartz** [solid/solid#48]
Solid somehow should participate in GSoC 2016.

Mentoring organization application deadline: 19 February 19:00 UTC
Timeline: https://developers.google.com/open-source/gsoc/timeline

Anybody willing to help with organizing this?

**Comment by csarven** [comment]
Great idea!

**Comment by akuckartz** [comment]
I am interested in helping to mentor something for the OpenGovLD specification project: https://github.com/OpenGovLD/specs/issues/122 Maybe some synergy with Solid is possible.

**Comment by akuckartz** [comment]
Now there exists a Solid Wiki page for GSoC 2016:
https://github.com/solid/solid/wiki/GSoC-2016

**Comment by nicola** [comment]
very great idea!

**Comment by csarven** [comment]
@akuckartz I've been toying with the idea of running everything under http://270a.info/ (multiple data endpoints, ~3.5 billion triples across) with a Solid server - I'm not completely sure if that even makes sense at this point. However, there is also a high overlap there with OpenGovLD. I'm open to suggestions as to if/how that coordination could work.

**Comment by dmitrizagidulin** [comment]
Sounds like the deadline for participation is passed. Can this issue be closed?
