### ISSUE TITLE
Implement server-side /logout functionality

### ISSUE THREAD

**Issue by dmitrizagidulin** [solid/solid#5]
(Moved from https://github.com/solid/solid-spec/issues/74).
**WebID-OIDC:**
- [ ] `node-solid-server`: [issue #388 - Implement logout](https://github.com/solid/node-solid-server/issues/388)

**WebID-TLS:** - Not currently possible, won't implement.

During the current WebID-TLS workflow, there's no way for a client to request to Log Out (stop authenticating as a particular WebID user / certificate).

**Comment by bblfish** [comment]
Sadly not possible currently, except for Firefox. That's a problem with client (browser) implementations as they keep sending the same certificate to the server. This would require the browser to have a log out functionality, but there is at present little chance of that happening.

**Comment by dmitrizagidulin** [comment]
From what I understand, the server can break the TLS connection, no?

**Comment by bblfish** [comment]
yes, but it does not help if the browser keeps sending it back. I really tried a lot of things there.

**Comment by dmitrizagidulin** [comment]
If it turns out that there's no possible way to log out using WebID-TLS, then we definitely need an alternate mechanism.

**Comment by bblfish** [comment]
Or put pressure on browser vendors to do the right thing. 
We do have alternatives such as [http-signature](https://github.com/solid/solid-spec/issues/52).

**Comment by rhiaro** [comment]
+1 requiring it to be possible to log out as a criteria for the auth mechanism we use...

(related https://github.com/linkeddata/dokieli/issues/74)

**Comment by bblfish** [comment]
+1 for requiring chrome support of identity to avoid phishing and other misuses.

**Comment by bblfish** [comment]
Actually in Google Chrome you can log out: you do that by opening a new Persona tab. That's the one way to think of it.

**Comment by dmitrizagidulin** [comment]
See also the `node-solid-server`+OIDC specific issue [#388 - Implement logout](https://github.com/solid/node-solid-server/issues/388)

**Comment by dmitrizagidulin** [comment]
Kicking over to @deiu for the rest of the functionality. (non-oidc related)

**Comment by kjetilk** [comment]
So, is this connected to the work we're currently doing on logout?

**Comment by dmitrizagidulin** [comment]
This has been implemented by various Solid server implementations. Closing.
