### ISSUE TITLE
do we need acl:Control?

### ISSUE THREAD

**Issue by bblfish** [solid/solid#51]
I implemented [WebAccessControl](https://www.w3.org/wiki/WebAccessControl) in [rww-play](https://github.com/read-write-web/rww-play) but could not find a use for acl:Control. I had trouble at the time also quite understanding how it would work. If I remember correctly its aim was to specifying access control restrictions on the acl file itself.

I was able to do without by specifying the following generic acls `wac:include`ed from other acls. Though one could do it on a case by case basis too.

```Turtle
[] acl:accessToClass [ acl:regex "https://jack.example/.*[.]acl" ];
   acl:mode acl:Read;
   acl:agentClass foaf:Agent .
[] acl:accessToClass [ acl:regex "https://jack.example/.*" ];
   acl:mode acl:Write, acl:Read;
   acl:agent <card#me> .
```

Presumably the acl file should specify itself as its own acl file in the http `Link`header (I don't think I have implemented that there.) Off the top of my head this should do:

```
Link: <>; rel="acl"
```

**Comment by bblfish** [comment]
In [issue 28](https://github.com/solid/solid/issues/28#issuecomment-177188242) @Stebalien uses `acl:Control` like this:

```Turtle
[acl:accessTo </malory-file-a>; <acl:agent> <Malory>; acl:mode acl:Control].
```

As I understand this is meant to say: Malory can edit the acl of the file `<malory-file-a>`. This seems
a very roundabout way to giving access to an acl. The solution I proposed in the initial post to this thread seems much more concise and elegant, as it does not require this extra indirection through an acl.

**Comment by bblfish** [comment]
@stebalien can you simplify the example you put forward in [issue 28](https://github.com/solid/solid/issues/28) as far as possible - start off with all acls being world visible for example - without `wac:Control` and specifying which files have which acls.

**Comment by timbl** [comment]
Yes, we do need Control.
You say "This seems a very roundabout way to giving access to an acl. "  Well, to me it seems a simple way.  Please implement it as is.
It saves having ACL files for ACL files, which obviously would be recursive.
The ACL system seems to be working well.  Closing this isssue

**Comment by bblfish** [comment]
The way of solving the acl of an acl would be simply to have the Link header point to itself.

```
Link: <>; rel="acl"
```

Then the file can simply write

```Turtle
[] acl:accessTo <>;
   acl:mode acl:Write, acl:Read;
   acl:agent <card#me> .
```

That does not even require regular expressions or pattern matching. 
I'll just re-open as the pattern matching may have been the reason for closing the issue. It's not always easy to get down to the core of an argument.

**Comment by deiu** [comment]
As @timbl said, we are switching to `acl:Control` for managing / controlling access to the ACL document.

**Comment by bblfish** [comment]
A bit of explanation as to why the reasons I give are wrong would have been appreciated.

**Comment by akuckartz** [comment]
I too have difficulties to understand the resolution of this issue.

**Comment by timbl** [comment]
I imagine that @deiu closed the issue because @bblfish was talking about not understanding the design at the top, which is not in itself an issue with the spec, and further down about arbitrary alternative designs. When something like acl:Control has been a consensus for a while and implemented multiple places,  it is not constructive to bring up issues like this, which just wonder about the design,  unless a severe reason has been found why the design itself would have a serious failure mode.  We need to move forward.

**Comment by bblfish** [comment]
I have [an implementation](https://github.com/read-write-web/rww-play) that does not use `acl:Control` and that gives me exactly the same features as what I understand `acl:Control` does, without adding any new features other than the acl header pointing to itself, which is useful [for other reasons in any case](https://github.com/solid/solid/issues/61).

So as a result I was not sure if I had misunderstood the meaning of `acl:Control`, since having redundant features in a design is usually frowned upon, and leads to more code and hence more failure modes.

**Comment by sandhawke** [comment]
The problem I see with ACLs on ACL resources is the end-user mental model.  I suspect must users will find it quite confusing.   But maybe not.   I wonder if there's a reasonable way for us to test that.

Also, will the spec say the acl for an acl is always itself, or is the server free to put it somewhere else?  If it's always itself the code can be pretty simple, yes.

On the other side, the problem I see with acl: Control is that it's ready to imagine wanting to make an ACL visible to someone without giving them write access.

**Comment by bblfish** [comment]
> the problem I see with acl: Control is that it's easy to imagine wanting to make an ACL visible to someone without giving them write access.

Good point, I had forgotten that restriction. There is a very good use case to make ACLs readable, without making them writeable, as described in [Client Authentication Discovery](https://github.com/read-write-web/SoLiD/wiki/Client-Authentication-Discovery#web-access-control-files).

> The problem I see with ACLs on ACL resources is the end-user mental model.

Actually it is quite simple: __"every resource has an ACL (even if it is its own ACL)"__ .  

Anyone who understand the current WAC already understands this. The only thing is that it is not stated explicitly that the acl files are currently their own acl files. That this is the case implicity though can be shown as follows: by making a change in an acl resource. E.g. by changing say  `<document.acl>` from

```Turtle
[] acl:accessTo <document>;
   acl:mode acl:Control;
   acl:agent <card#me>
```

to

```Turtle
[] acl:accessTo <document>;
   acl:mode acl:Control;
   acl:agent timbl .
```

one has actually changed the rights to the `<document.acl>`, and not necessarily those to `<document>`. So the acl is its own acl: with `wac:Control` it is just expressing it in a pretty round about manner.

> Also, will the spec say the acl for an acl is always itself, or is the server free to put it somewhere else? If it's always itself the code can be pretty simple, yes.

There are use case for having every resource have an one or more ACL headers [described in issue #61](https://github.com/solid/solid/issues/61). 

I think the code to implement this should be quite easy:  Every resource is treated the same way. On a request to the server for an action such `GET` on a resource `</document>` the Guard 

1. Does a `HEAD` on the resource to find its acl header, if none is there it does not give access.
2. If there is one or more  `rel="acl"`  Link it does a request on each of those resources, and finds out if it or its `wac:inlcuded` resources give the right access on the initially requested resource.

So if the request is for an acl, eg `<document.acl>` which declares itself to be its own acl, then __1__ above will return the resource itself, and the server that has access to the resource will be able to get the document itself and continue with 2.

The client who may be using the same code may not be able to move to __2__ if it is not granted access by the server to read that resource. But well in that case it already knows it does not have access. What it cannot know is what identity it could use to gain access.

The closer the guard is to the resource itself, the less leakage of acl info there will be across the server memory.

I am happy to say that at least the dev branch of rww-play actually works like this:

```bash
$ curl -i -k -H "Accept: text/turtle" https://joe.example:8443/2013/card.acl
HTTP/1.1 200 OK
Accept-Patch: application/sparql-update
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Authorization,Host,User,Signature-Date,*
Access-Control-Allow-Origin: *
Allow: OPTIONS, GET, HEAD, SEARCH, PUT, DELETE, PUT, PATCH
Content-Type: text/turtle
ETag: "1454695031000|Success(1404)"
Last-Modified: Fri, 05 Feb 2016 17:57:11 GMT
Link: <http://www.w3.org/ns/ldp#Resource>; rel=type, <card.acl>; rel=acl
Set-Cookie: PLAY_SESSION=c8a803396ccf3915fce4febee889d906947f66cb-subject=; Path=/; HTTPOnly
Content-Length: 538

...
```
