### ISSUE TITLE
regexes in ACLs

### ISSUE THREAD

**Issue by bblfish** [solid/solid#52]
[rww-play](https://github.com/read-write-web/rww-play) implements regexes for WebAccessControl as lightly documented on [the WebAccessControl wiki page](https://www.w3.org/wiki/WebAccessControl). This allows one to set access controls for a whole number of resources in a space.

An example given in  [issue 51: Do we need wac:Control](https://github.com/solid/solid/issues/51) is

```
[] acl:accessToClass [ acl:regex "https://jack.example/.*[.]acl" ];
   acl:mode acl:Read;
   acl:agentClass foaf:Agent .
[] acl:accessToClass [ acl:regex "https://jack.example/.*" ];
   acl:mode acl:Write, acl:Read;
   acl:agent <card#me> .
```

the implementation is quite simple [in WACAuthZ](https://github.com/read-write-web/rww-play/blob/901a5250e9e62d101265cdb9a57c36b7f6623bd3/app/rww/ldp/auth/WACAuthZ.scala#L114) mostly because it relies on Java Regular Expressions. JS Regular expressions work differently, and may also be different to [Powder regex](https://www.w3.org/TR/powder-dr/#formalSemantics). 

This is quite powerful, as shown in the example above. But perhaps there is no need for something quite that powerful and a simpler regex language would do, that may not have the complexity of regular expressions which can be turing complete (verify).

Issue: the above example does require a client to know that the ACL for a resource has a particular extension. How would it find that out?

**Comment by sandhawke** [comment]
While I personally love regexps, and expressive power in general, my sense is they're far too error prone to be suitable for permissions.      Plus, as you point out, they have to take into account how ACL resources (and meta data resources) are assigned names by the server.   So I'd suggest we hold off on including them until/unless an overwhelming use case appears.

**Comment by bblfish** [comment]
Yes of course, full regexes are too powerful. It's a good place to start with to try out ideas.
I have opened a wiki to list use cases for it so that we can then work out what the simplest language that we actually need would be. [wiki page: Regexes in ACLs](https://github.com/solid/solid/wiki/Regexes-in-ACLs)

As far as making the group of acls available to the client this could be done in a number of ways, of which a `.well-known` space describing the SoLiD server. This could then contain a named group describing all the acls with a graph such as this:

```Turtle
<#acls> a AclGroup;
    forOrigin <https://jack.example>;
    acl:regex "https://jack.example/.*[.]acl" .
```

**Comment by dmitrizagidulin** [comment]
Double-checked with @deiu and @timbl, the consensus currently is that Solid implementations will not support regexes in ACLs.
(Marking this as 'pending closing'.)
