### ISSUE TITLE
Document proposal-based Solid project workflow

### ISSUE THREAD

**Issue by dmitrizagidulin** [solid/solid#55]
- [x] Create `/proposals` folder in this repo.
- [ ] Move existing discussion/proposal `.md` docs from `solid-spec` and into individual PRs to `solid/solid`.
- [ ] Add documentation of the process into the READMEs of `solid/solid` and `solid/spec`

**Comment by sandhawke** [comment]
This seems pretty heavyweight before there's a serious external userbase.

**Comment by dmitrizagidulin** [comment]
What we lack in external userbase, we make up in contentious arguments :)

**Comment by sandhawke** [comment]
Right, but this process is geared to help with external userbase.   I doesn't seem to help at all with the contentious arguments problem.

**Comment by dmitrizagidulin** [comment]
What aspects of our current situation would you like to see addressed? Do you have an alternative mechanism in mind?

**Comment by dmitrizagidulin** [comment]
This issue was related to an early governance proposal. It is now superceded by the governance framework over at https://github.com/solid/process. Closing.
