### ISSUE TITLE
Move 'WebID+RSA' spec section to /proposals

### ISSUE THREAD

**Issue by dmitrizagidulin** [solid/solid#62]
Since the [WebID+RSA](https://github.com/solid/solid-spec/#webid-rsa) section is still in the experimental/proposal stage, let's move it to `solid/solid/proposals`.

**Comment by bblfish** [comment]
+1 I'd like to add a "competing" proposal based on [Http-Signature](https://github.com/solid/solid-spec/issues/52).

**Comment by dmitrizagidulin** [comment]
@bblfish please do.

**Comment by deiu** [comment]
:+1:

**Comment by dmitrizagidulin** [comment]
Merged, closing.
