### ISSUE TITLE
Move 'WebID Delegated Requests' spec section to proposals

### ISSUE THREAD

**Issue by dmitrizagidulin** [solid/solid#63]
Since the [WebID Delegated Requests](https://github.com/solid/solid-spec/#webid-delegated-requests) section is experimental / not yet implemented, and requires further discussion, let's move it to `solid/solid/proposals`.

**Comment by bblfish** [comment]
+1

**Comment by deiu** [comment]
:+1:

**Comment by dmitrizagidulin** [comment]
Merged, closing.
