### ISSUE TITLE
WWW-Authenticate and WebID-RSA

### ISSUE THREAD

**Issue by mansoure** [solid/solid#75]
If a user try to access a restricted LDP resource, such as get essam.meccano.io, meccano responses by 401 and build a response like the following: 

Accept-Patch: application/json
Accept-Post: text/turtle;charset=utf-8,text/n3;charset=utf-8,text/nt;charset=utf-8,text/css;charset=utf-8,text/html;charset=utf-8,text/javascript;charset=utf-8,text/plain;charset=utf-8,application/rdf+xml;charset=utf-8,application/json;charset=utf-8,multipart/form-data,image/jpeg,image/jpeg,image/png,image/gif,font/otf
**Access-Control-Allow-Credentials**: true
Access-Control-Allow-Origin: http://linkeddata.github.io
Access-Control-Expose-Headers: User, Location, Link, Vary, Last-Modified, WWW-Authenticate, Content-Length, Accept-Patch, Accept-Post, Allow, Updates-Via, Ms-Author-Via
Connection: keep-alive
Content-Type: text/turtle
Date: Wed, 17 Feb 2016 07:25:29 GMT
Link: <https://essam.meccano.io/,acl>; rel=acl
Server: nginx/1.4.6 (Ubuntu)
Transfer-Encoding: chunked
User: https://essam.meccano.io/profile/card#me
Vary: Accept,Origin
**WWW-Authenticate**: WebID-RSA source="meccano.io", nonce="token123"

I am expecting the browser is to open a popup window to select a specific certificate. However, it does not.

If I give for WWW-Authenticate the value Basic realm, the browser opens a popup window asking for a user account and password. 

I have been investigating to know why in the case of   WebID-RSA, it does not open a popup window to select a specific certificate.

I also would like to be sure what is the correct source to be used, for  WebID-RSA source=.

BTW, the current nonce value is just for testing.

**Comment by deiu** [comment]
Have you had a chance to look at https://github.com/solid/solid/blob/master/proposals/auth-webid-rsa.md?

**Comment by mansoure** [comment]
Yes! When I searched google for  "WWW-Authenticate" + "WebID-RSA", it was the first link I got. 
I also went through the Gold code and I followed the steps in https://github.com/linkeddata/gold/blob/183d0aea9ae2020aefbe62ec3d599bba3d0192c7/acl.go

wwwAuth := `WebID-RSA source="` + acl.req.BaseURI() + `", nonce="` + token + `"`
				acl.w.Header().Set("WWW-Authenticate", wwwAuth)
				return 401, errors.New("Access to " + p.URI + " requires authentication")

As you see in the above response built by meccano for accessing essam.meccano.io

I have 
Access-Control-Allow-Credentials: true
WWW-Authenticate: WebID-RSA source="meccano.io", nonce="token123"

But still, the browser does not popup the window to select a certificate. Instead, the got this  error in WARP:
"Could not fetch dir listing. HTTP 401"

So, it seems I am missing something.

Is it something related to the response or something else ?

**Comment by nicola** [comment]
@mansoure thanks for writing down your procedure.

@deiu can confirm if I am correct, but in WebID-RSA, differently from WebID-TLS there is no certificate pop-up happening in the browser. The browser should store its private key in the local storage (in a trusted origin), patch its webid with the new key. Now, when signing in into any pod, they should use this key (very likely via `postMessage`) and then they should use this key to sign the request.

Please feel free to ask any other question

-- 
A side note on ldnode - we decided to delay the implementation of webid+rsa until we finalized authentication!

**Comment by mansoure** [comment]
But when I try to access my account at databox.me; essam.databox.me. The browser does popup a window to select a certificate. I tracked the gold code, it append  "WWW-Authenticate: WebID-RSA source=" to the header of its response. 

I am doing "the same", as I believe :) but I get this error instead of the popup window. The error ** "Could not fetch dir listing. HTTP 401"**

Any idea where I should investigate ?

**Comment by nicola** [comment]
@mansoure databox is trying to advertise two ways of authenticating:

1) WebID-TLS: the fact that there is a popup to select the certificate is because the databox.me server is requiring a certificate for the WebID-TLS authentication. Passing the certificate will in fact trigger a TLS authentication.

2) WebID-RSA: beyond to the request for the certificate, Databox is also advertising the fact that you may authenticate via WebID-RSA, so if you wanted to do so, you could get the nonce from WWW-Authenticate and proceed as the [proposal](https://github.com/solid/solid/blob/master/proposals/auth-webid-rsa.md) suggests

**Comment by nicola** [comment]
@mansoure can I consider this solved?

**Comment by mansoure** [comment]
@nicola Thanks for asking! Yes, you can. As you advised, I will implement WebID-TLS. 
Sorry for the late reply as I did not get a notification.
