### ISSUE TITLE
Solid Modularity: Clarify and Reduce Dependencies

### ISSUE THREAD

**Issue by sandhawke** [solid/solid#93]
Issue #72 was closed without addressing my concern.    I'll see if I can make it more clear.

I think each module should be specified with minimal dependencies on other modules, and no reference to solid.   Then solid can important the modules it wants.   And other people can use the modules if they want to, in other contexts.

Each module should be suitable for being on the standards track at IETF, W3C, or some other similar organization, depending on the type of module it is.

A dependency diagram of the modules should be a fairly nice looking tree.

**Comment by elf-pavlik** [comment]
I plan to implement some of Solid modules, and mix them with
* [Linked Data Fragments](http://linkeddatafragments.org/)
  * [Triple Pattern Fragment](http://www.hydra-cg.com/spec/latest/triple-pattern-fragments/)
* [HTTP Signatures](http://tools.ietf.org/html/draft-cavage-http-signatures-05)
* [Hydra](http://hydra-cg.com/)
* [Void](https://www.w3.org/TR/void/)

Very likely also support to some extent [Activity Streams 2.0](https://www.w3.org/TR/activitystreams-core/) and [Schema.org](http://schema.org)

As long as people ensure [URI persistence](https://www.w3.org/TR/webarch/#URI-persistence) all the rest needs to stay open to evolve. Including terms used in vocabularies for example via constructs like [schema:supersededBy](https://schema.org/supersededBy)

**Comment by sandhawke** [comment]
After more thought, I don't think this is for solid to do.

**Comment by dmitrizagidulin** [comment]
@sandhawke - I was gonna ask, aside from Web Access Control, which is gonna get its own repo shortly, did you have particular sections in mind, to move their specs to separate repos?

**Comment by sandhawke** [comment]
@dmitrizagidulin I started #72 with a rough list.   I'm working on a more careful one.   The granularity I'm aiming for at the level of one might reasonably implement or not implement.  So people would naturally do all of a module or none of a module, without significant motivation for implementing part of a module.
